2021-12-02T19:25:10|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\hardware.py", line 220, in enable_connection
    raise err
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\hardware.py", line 210, in enable_connection
    self.connect()
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\aist_nt_remote_spm_rpc\remote_spm_hw.py", line 36, in connect
    raise RuntimeError(f"{self.name} Invalid proxy - Make sure macros is running")
RuntimeError: remote_spm_hw Invalid proxy - Make sure macros is running

2021-12-02T19:35:35|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\hardware.py", line 220, in enable_connection
    raise err
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\hardware.py", line 210, in enable_connection
    self.connect()
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\aist_nt_remote_spm_rpc\remote_spm_hw.py", line 45, in connect
    self.communicator = open(Ice.initialize(sys.argv, 'config.client'))
TypeError: expected str, bytes or os.PathLike object, not CommunicatorI

2021-12-02T19:36:01|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\hardware.py", line 220, in enable_connection
    raise err
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\hardware.py", line 210, in enable_connection
    self.connect()
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\aist_nt_remote_spm_rpc\remote_spm_hw.py", line 45, in connect
    self.communicator = open(Ice.initialize(sys.argv, "config.client"))
TypeError: expected str, bytes or os.PathLike object, not CommunicatorI

