2021-12-02T19:39:26|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\hardware.py", line 220, in enable_connection
    raise err
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\hardware.py", line 210, in enable_connection
    self.connect()
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\aist_nt_remote_spm_rpc\remote_spm_hw.py", line 51, in connect
    raise RuntimeError(f"{self.name} Invalid proxy")
RuntimeError: remote_spm_hw Invalid proxy

2021-12-02T19:39:44|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\hardware.py", line 220, in enable_connection
    raise err
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\hardware.py", line 210, in enable_connection
    self.connect()
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\aist_nt_remote_spm_rpc\remote_spm_hw.py", line 51, in connect
    raise RuntimeError(f"{self.name} Invalid proxy")
RuntimeError: remote_spm_hw Invalid proxy

2021-12-02T19:39:53|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\hardware.py", line 220, in enable_connection
    raise err
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\hardware.py", line 210, in enable_connection
    self.connect()
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\aist_nt_remote_spm_rpc\remote_spm_hw.py", line 51, in connect
    raise RuntimeError(f"{self.name} Invalid proxy")
RuntimeError: remote_spm_hw Invalid proxy

2021-12-02T19:41:03|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\hardware.py", line 220, in enable_connection
    raise err
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\hardware.py", line 210, in enable_connection
    self.connect()
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\aist_nt_remote_spm_rpc\remote_spm_hw.py", line 51, in connect
    raise RuntimeError(f"{self.name} Invalid proxy")
RuntimeError: remote_spm_hw Invalid proxy

2021-12-02T19:41:12|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\hardware.py", line 220, in enable_connection
    raise err
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\hardware.py", line 210, in enable_connection
    self.connect()
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\aist_nt_remote_spm_rpc\remote_spm_hw.py", line 51, in connect
    raise RuntimeError(f"{self.name} Invalid proxy")
RuntimeError: remote_spm_hw Invalid proxy

2021-12-02T19:42:10|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\hardware.py", line 220, in enable_connection
    raise err
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\hardware.py", line 210, in enable_connection
    self.connect()
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\aist_nt_remote_spm_rpc\remote_spm_hw.py", line 53, in connect
    remote_spm.setProperty("Ice.ACM.Client", "0")
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\aist_nt_remote_spm_rpc\RemoteSpm_ice.py", line 31, in setProperty
    return _M_RemoteSpmRPC.RemoteSpm._op_setProperty.invoke(self, ((prop, val), context))
Ice.OperationNotExistException: exception ::Ice::OperationNotExistException
{
    id = 
    {
        name = myTestAdapter
        category = 
    }
    facet = 
    operation = setProperty
}

2021-12-02T19:43:01|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\hardware.py", line 220, in enable_connection
    raise err
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\hardware.py", line 210, in enable_connection
    self.connect()
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\aist_nt_remote_spm_rpc\remote_spm_hw.py", line 53, in connect
    remote_spm.setProperty("Ice.ACM.Client", "0")
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\aist_nt_remote_spm_rpc\RemoteSpm_ice.py", line 31, in setProperty
    return _M_RemoteSpmRPC.RemoteSpm._op_setProperty.invoke(self, ((prop, val), context))
Ice.OperationNotExistException: exception ::Ice::OperationNotExistException
{
    id = 
    {
        name = myTestAdapter
        category = 
    }
    facet = 
    operation = setProperty
}

