2019-06-13T22:33:10|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\lab\.p2\pool\plugins\org.python.pydev.core_6.4.4.201807281807\pysrc\pydevd.py", line 1709, in <module>
    main()
  File "C:\Users\lab\.p2\pool\plugins\org.python.pydev.core_6.4.4.201807281807\pysrc\pydevd.py", line 1703, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Users\lab\.p2\pool\plugins\org.python.pydev.core_6.4.4.201807281807\pysrc\pydevd.py", line 1050, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "C:\Users\lab\.p2\pool\plugins\org.python.pydev.core_6.4.4.201807281807\pysrc\pydevd.py", line 1057, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Users\lab\.p2\pool\plugins\org.python.pydev.core_6.4.4.201807281807\pysrc\_pydev_imps\_pydev_execfile.py", line 25, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:\Users\lab\Documents\foundry_scope\ScopeFoundryHW\picoquant\hydraharp_test_app.py", line 18, in <module>
    app = HydraHarpTestApp()
  File "C:\Users\lab\Documents\foundry_scope\ScopeFoundry\base_app.py", line 338, in __init__
    self.setup()
  File "C:\Users\lab\Documents\foundry_scope\ScopeFoundryHW\picoquant\hydraharp_test_app.py", line 16, in setup
    self.add_measurement(TRPL2DScan(self))
  File "C:\Users\lab\Documents\foundry_scope\ScopeFoundryHW\picoquant\trpl_2d_scan_base.py", line 277, in __init__
    DummyStageBase2DScan.__init__(self, app)
  File "C:\Users\lab\Documents\foundry_scope\ScopeFoundry\scanning\base_raster_scan.py", line 56, in __init__
    Measurement.__init__(self, app)
  File "C:\Users\lab\Documents\foundry_scope\ScopeFoundry\measurement.py", line 93, in __init__
    self.setup()
  File "C:\Users\lab\Documents\foundry_scope\ScopeFoundryHW\picoquant\trpl_2d_scan_base.py", line 281, in setup
    DummyStageBase2DScan.setup(self)
  File "C:\Users\lab\Documents\foundry_scope\ScopeFoundryHW\picoquant\trpl_2d_scan_base.py", line 268, in setup
    self.stage = self.app.hardware['dummy_xy_stage']
  File "C:\Users\lab\Documents\foundry_scope\ScopeFoundry\helper_funcs.py", line 31, in __getitem__
    return self._odict[key]
KeyError: 'dummy_xy_stage'

