2021-11-15T17:01:12|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\RAMAN\.p2\pool\plugins\org.python.pydev.core_7.5.0.202001101138\pysrc\pydevd.py", line 3129, in <module>
    main()
  File "C:\Users\RAMAN\.p2\pool\plugins\org.python.pydev.core_7.5.0.202001101138\pysrc\pydevd.py", line 3122, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Users\RAMAN\.p2\pool\plugins\org.python.pydev.core_7.5.0.202001101138\pysrc\pydevd.py", line 2195, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "C:\Users\RAMAN\.p2\pool\plugins\org.python.pydev.core_7.5.0.202001101138\pysrc\pydevd.py", line 2202, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Users\RAMAN\.p2\pool\plugins\org.python.pydev.core_7.5.0.202001101138\pysrc\_pydev_imps\_pydev_execfile.py", line 25, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:\Users\RAMAN\workspace\NearField\NearFieldMicroscope\near_field_microscope_app.py", line 199, in <module>
    app = NearFieldMicroscope(sys.argv)
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\base_app.py", line 338, in __init__
    self.setup()
  File "C:\Users\RAMAN\workspace\NearField\NearFieldMicroscope\near_field_microscope_app.py", line 110, in setup
    from confocal_measure.power_scan import PowerScanMeasure
  File "C:\Users\RAMAN\workspace\NearField\confocal_measure\__init__.py", line 3, in <module>
    from .apd_mcl_2dslowscan import APD_MCL_2DSlowScan
  File "C:\Users\RAMAN\workspace\NearField\confocal_measure\apd_mcl_2dslowscan.py", line 1, in <module>
    from ScopeFoundryHW.mcl_stage import MCLStage2DSlowScan
ModuleNotFoundError: No module named 'ScopeFoundryHW.mcl_stage'

