2022-01-31T12:05:27|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\hardware.py", line 210, in enable_connection
    self.connect()
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\dynamixel_servo\dynamixel_x_servo_hw.py", line 37, in connect
    self.dev = DynamixelServos(port=self.settings['port'])
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\dynamixel_servo\dynamixel_x_servo.py", line 111, in __init__
    success = self.portHandler.openPort()
  File "C:\ProgramData\Anaconda3\lib\site-packages\dynamixel_sdk\port_handler.py", line 44, in openPort
    return self.setBaudRate(self.baudrate)
  File "C:\ProgramData\Anaconda3\lib\site-packages\dynamixel_sdk\port_handler.py", line 68, in setBaudRate
    return self.setupPort(baud)
  File "C:\ProgramData\Anaconda3\lib\site-packages\dynamixel_sdk\port_handler.py", line 120, in setupPort
    timeout=0
  File "C:\ProgramData\Anaconda3\lib\site-packages\serial\serialwin32.py", line 33, in __init__
    super(Serial, self).__init__(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\serial\serialutil.py", line 244, in __init__
    self.open()
  File "C:\ProgramData\Anaconda3\lib\site-packages\serial\serialwin32.py", line 64, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM10': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\hardware.py", line 231, in enable_connection
    self.tree_item.setText(1,'X')
AttributeError: 'DynamixelXServosHW' object has no attribute 'tree_item'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\hardware.py", line 235, in enable_connection
    self.tree_item.setText(1,'?')
AttributeError: 'DynamixelXServosHW' object has no attribute 'tree_item'

2022-01-31T12:05:27|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\hardware.py", line 210, in enable_connection
    self.connect()
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\dynamixel_servo\dynamixel_x_servo_hw.py", line 37, in connect
    self.dev = DynamixelServos(port=self.settings['port'])
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\dynamixel_servo\dynamixel_x_servo.py", line 111, in __init__
    success = self.portHandler.openPort()
  File "C:\ProgramData\Anaconda3\lib\site-packages\dynamixel_sdk\port_handler.py", line 44, in openPort
    return self.setBaudRate(self.baudrate)
  File "C:\ProgramData\Anaconda3\lib\site-packages\dynamixel_sdk\port_handler.py", line 68, in setBaudRate
    return self.setupPort(baud)
  File "C:\ProgramData\Anaconda3\lib\site-packages\dynamixel_sdk\port_handler.py", line 120, in setupPort
    timeout=0
  File "C:\ProgramData\Anaconda3\lib\site-packages\serial\serialwin32.py", line 33, in __init__
    super(Serial, self).__init__(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\serial\serialutil.py", line 244, in __init__
    self.open()
  File "C:\ProgramData\Anaconda3\lib\site-packages\serial\serialwin32.py", line 64, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM10': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\hardware.py", line 254, in on_connection_failed
    self.tree_item.setText(1,'!')
AttributeError: 'DynamixelXServosHW' object has no attribute 'tree_item'

2022-01-31T12:05:27|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\hardware.py", line 220, in enable_connection
    raise err
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\hardware.py", line 210, in enable_connection
    self.connect()
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\dynamixel_servo\dynamixel_x_servo_hw.py", line 37, in connect
    self.dev = DynamixelServos(port=self.settings['port'])
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\dynamixel_servo\dynamixel_x_servo.py", line 111, in __init__
    success = self.portHandler.openPort()
  File "C:\ProgramData\Anaconda3\lib\site-packages\dynamixel_sdk\port_handler.py", line 44, in openPort
    return self.setBaudRate(self.baudrate)
  File "C:\ProgramData\Anaconda3\lib\site-packages\dynamixel_sdk\port_handler.py", line 68, in setBaudRate
    return self.setupPort(baud)
  File "C:\ProgramData\Anaconda3\lib\site-packages\dynamixel_sdk\port_handler.py", line 120, in setupPort
    timeout=0
  File "C:\ProgramData\Anaconda3\lib\site-packages\serial\serialwin32.py", line 33, in __init__
    super(Serial, self).__init__(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\serial\serialutil.py", line 244, in __init__
    self.open()
  File "C:\ProgramData\Anaconda3\lib\site-packages\serial\serialwin32.py", line 64, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM10': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)

2022-01-31T12:05:27|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\dynamixel_servo\dynamixel_single_hw.py", line 67, in set_mode
    self.servos.settings[S['servo_name']+'_torque'] = False
AttributeError: 'DynamixelServoHW' object has no attribute 'servos'

2022-01-31T12:05:27|INFO|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer start_stop False
2022-01-31T12:05:27|INFO|HydraHarpOptimizerMeasure|measurement hydraharp_channel_optimizer stopping stop_first
2022-01-31T12:05:27|INFO|HydraHarpHistogramMeasure|hydraharp_histogram start_stop False
2022-01-31T12:05:27|INFO|HydraHarpHistogramMeasure|measurement hydraharp_histogram stopping stop_first
2022-01-31T12:05:27|INFO|PowerScanMeasure|power_scan start_stop False
2022-01-31T12:05:27|INFO|PowerScanMeasure|measurement power_scan stopping stop_first
2022-01-31T12:05:27|INFO|PowerMeterOptimizerMeasure|powermeter_optimizer start_stop False
2022-01-31T12:05:27|INFO|PowerMeterOptimizerMeasure|measurement powermeter_optimizer stopping stop_first
2022-01-31T12:05:27|INFO|Sequencer|sequencer start_stop False
2022-01-31T12:05:27|INFO|Sequencer|measurement sequencer stopping stop_first
2022-01-31T12:05:27|INFO|APDOptimizerCBMeasurement|apd_optimizer start_stop False
2022-01-31T12:05:27|INFO|APDOptimizerCBMeasurement|measurement apd_optimizer stopping stop_first
2022-01-31T12:05:27|INFO|NearFieldMicroscope|setting up figures for hydraharp_channel_optimizer measurement hydraharp_channel_optimizer
2022-01-31T12:05:27|INFO|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer start_stop False
2022-01-31T12:05:27|INFO|HydraHarpOptimizerMeasure|measurement hydraharp_channel_optimizer stopping stop_first
2022-01-31T12:05:27|INFO|NearFieldMicroscope|setting up figures for hydraharp_histogram measurement hydraharp_histogram
2022-01-31T12:05:27|INFO|NearFieldMicroscope|setting up figures for power_scan measurement power_scan
2022-01-31T12:05:27|INFO|PowerScanMeasure|power_scan start_stop False
2022-01-31T12:05:27|INFO|PowerScanMeasure|measurement power_scan stopping stop_first
2022-01-31T12:05:27|INFO|NearFieldMicroscope|setting up figures for powermeter_optimizer measurement powermeter_optimizer
2022-01-31T12:05:27|INFO|PowerMeterOptimizerMeasure|powermeter_optimizer start_stop False
2022-01-31T12:05:28|INFO|PowerMeterOptimizerMeasure|measurement powermeter_optimizer stopping stop_first
2022-01-31T12:05:28|INFO|NearFieldMicroscope|setting up figures for sequencer measurement sequencer
2022-01-31T12:05:28|INFO|Sequencer|sequencer start_stop False
2022-01-31T12:05:28|INFO|Sequencer|measurement sequencer stopping stop_first
2022-01-31T12:05:28|WARNING|HydraHarpOptimizerMeasure|Measurement.gui is deprecated, use Measurement.app <class 'DeprecationWarning'>
2022-01-31T12:05:28|WARNING|HydraHarpHistogramMeasure|Measurement.gui is deprecated, use Measurement.app <class 'DeprecationWarning'>
2022-01-31T12:05:28|WARNING|PowerScanMeasure|Measurement.gui is deprecated, use Measurement.app <class 'DeprecationWarning'>
2022-01-31T12:05:28|WARNING|PowerMeterOptimizerMeasure|Measurement.gui is deprecated, use Measurement.app <class 'DeprecationWarning'>
2022-01-31T12:05:28|WARNING|Sequencer|Measurement.gui is deprecated, use Measurement.app <class 'DeprecationWarning'>
2022-01-31T12:05:28|WARNING|APDOptimizerCBMeasurement|Measurement.gui is deprecated, use Measurement.app <class 'DeprecationWarning'>
2022-01-31T12:05:28|INFO|NearFieldMicroscope|setting up figures for apd_optimizer measurement apd_optimizer
2022-01-31T12:05:28|INFO|APDOptimizerCBMeasurement|apd_optimizer start_stop False
2022-01-31T12:05:28|INFO|APDOptimizerCBMeasurement|measurement apd_optimizer stopping stop_first
2022-01-31T12:05:28|INFO|NearFieldMicroscope|ini settings loading from near_field_microscope_defaults.ini
2022-01-31T12:05:28|DEBUG|FileLQ|save_dir: update_value 'C:\\Users\\RAMAN\\workspace\\NearField\\NearFieldMicroscope\\data' --> 'E:\\Natalie'    sender=None
2022-01-31T12:05:28|DEBUG|FileLQ|save_dir: different values C:\Users\RAMAN\workspace\NearField\NearFieldMicroscope\data E:\Natalie
2022-01-31T12:05:28|INFO|NearFieldMicroscope|hardware/hydraharp
2022-01-31T12:05:28|INFO|NearFieldMicroscope|hardware/thorlabs_powermeter
2022-01-31T12:05:28|INFO|NearFieldMicroscope|hardware/motorized_polarizer
2022-01-31T12:05:28|INFO|NearFieldMicroscope|hardware/apd_counter
2022-01-31T12:05:28|INFO|NearFieldMicroscope|hardware/dynamixel_servos
2022-01-31T12:05:28|INFO|NearFieldMicroscope|hardware/power_wheel
2022-01-31T12:05:28|INFO|NearFieldMicroscope|-->Failed to load config for hardware/power_wheel/pos_scale, new val 280: KeyError('pos_scale')
2022-01-31T12:05:28|INFO|NearFieldMicroscope|ini settings loaded from: near_field_microscope_defaults.ini
2022-01-31T12:05:33|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\hardware.py", line 220, in enable_connection
    raise err
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\hardware.py", line 210, in enable_connection
    self.connect()
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\dynamixel_servo\dynamixel_x_servo_hw.py", line 37, in connect
    self.dev = DynamixelServos(port=self.settings['port'])
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\dynamixel_servo\dynamixel_x_servo.py", line 111, in __init__
    success = self.portHandler.openPort()
  File "C:\ProgramData\Anaconda3\lib\site-packages\dynamixel_sdk\port_handler.py", line 44, in openPort
    return self.setBaudRate(self.baudrate)
  File "C:\ProgramData\Anaconda3\lib\site-packages\dynamixel_sdk\port_handler.py", line 68, in setBaudRate
    return self.setupPort(baud)
  File "C:\ProgramData\Anaconda3\lib\site-packages\dynamixel_sdk\port_handler.py", line 120, in setupPort
    timeout=0
  File "C:\ProgramData\Anaconda3\lib\site-packages\serial\serialwin32.py", line 33, in __init__
    super(Serial, self).__init__(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\serial\serialutil.py", line 244, in __init__
    self.open()
  File "C:\ProgramData\Anaconda3\lib\site-packages\serial\serialwin32.py", line 64, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM10': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)

2022-01-31T12:05:36|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\hardware.py", line 220, in enable_connection
    raise err
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\hardware.py", line 210, in enable_connection
    self.connect()
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\dynamixel_servo\dynamixel_x_servo_hw.py", line 37, in connect
    self.dev = DynamixelServos(port=self.settings['port'])
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\dynamixel_servo\dynamixel_x_servo.py", line 111, in __init__
    success = self.portHandler.openPort()
  File "C:\ProgramData\Anaconda3\lib\site-packages\dynamixel_sdk\port_handler.py", line 44, in openPort
    return self.setBaudRate(self.baudrate)
  File "C:\ProgramData\Anaconda3\lib\site-packages\dynamixel_sdk\port_handler.py", line 68, in setBaudRate
    return self.setupPort(baud)
  File "C:\ProgramData\Anaconda3\lib\site-packages\dynamixel_sdk\port_handler.py", line 120, in setupPort
    timeout=0
  File "C:\ProgramData\Anaconda3\lib\site-packages\serial\serialwin32.py", line 33, in __init__
    super(Serial, self).__init__(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\serial\serialutil.py", line 244, in __init__
    self.open()
  File "C:\ProgramData\Anaconda3\lib\site-packages\serial\serialwin32.py", line 64, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM10': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)

2022-01-31T12:05:37|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\hardware.py", line 220, in enable_connection
    raise err
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\hardware.py", line 210, in enable_connection
    self.connect()
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\dynamixel_servo\dynamixel_x_servo_hw.py", line 37, in connect
    self.dev = DynamixelServos(port=self.settings['port'])
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\dynamixel_servo\dynamixel_x_servo.py", line 111, in __init__
    success = self.portHandler.openPort()
  File "C:\ProgramData\Anaconda3\lib\site-packages\dynamixel_sdk\port_handler.py", line 44, in openPort
    return self.setBaudRate(self.baudrate)
  File "C:\ProgramData\Anaconda3\lib\site-packages\dynamixel_sdk\port_handler.py", line 68, in setBaudRate
    return self.setupPort(baud)
  File "C:\ProgramData\Anaconda3\lib\site-packages\dynamixel_sdk\port_handler.py", line 120, in setupPort
    timeout=0
  File "C:\ProgramData\Anaconda3\lib\site-packages\serial\serialwin32.py", line 33, in __init__
    super(Serial, self).__init__(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\serial\serialutil.py", line 244, in __init__
    self.open()
  File "C:\ProgramData\Anaconda3\lib\site-packages\serial\serialwin32.py", line 64, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM10': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)

2022-01-31T12:07:09|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\hardware.py", line 220, in enable_connection
    raise err
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\hardware.py", line 210, in enable_connection
    self.connect()
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\dynamixel_servo\dynamixel_single_hw.py", line 48, in connect
    for servo_pos,steps in zip([servos.settings.get_lq(S['servo_name']+'_position'),
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\logged_quantity.py", line 1431, in get_lq
    return self._logged_quantities[key]
KeyError: 'test2_position'

2022-01-31T12:47:37|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\logged_quantity.py", line 860, in update_math_reverse
    lq.update_value(new_val)
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\logged_quantity.py", line 274, in update_value
    self.hardware_set_func(self.val)
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\dynamixel_servo\dynamixel_x_servo_hw.py", line 63, in write_f
    self.dev.write_value(sid, ctrl.name, new_val)
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\dynamixel_servo\dynamixel_x_servo.py", line 151, in write_value
    raise IOError("DLX err: %s" % self.packetHandler.getRxPacketError(dxl_error))
OSError: DLX err: [RxPacketError] The data value exceeds the limit value!

2022-01-31T12:48:20|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\logged_quantity.py", line 860, in update_math_reverse
    lq.update_value(new_val)
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\logged_quantity.py", line 274, in update_value
    self.hardware_set_func(self.val)
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\dynamixel_servo\dynamixel_x_servo_hw.py", line 63, in write_f
    self.dev.write_value(sid, ctrl.name, new_val)
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\dynamixel_servo\dynamixel_x_servo.py", line 151, in write_value
    raise IOError("DLX err: %s" % self.packetHandler.getRxPacketError(dxl_error))
OSError: DLX err: [RxPacketError] The data value exceeds the limit value!

2022-01-31T13:07:16|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\logged_quantity.py", line 860, in update_math_reverse
    lq.update_value(new_val)
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\logged_quantity.py", line 274, in update_value
    self.hardware_set_func(self.val)
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\dynamixel_servo\dynamixel_x_servo_hw.py", line 63, in write_f
    self.dev.write_value(sid, ctrl.name, new_val)
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\dynamixel_servo\dynamixel_x_servo.py", line 151, in write_value
    raise IOError("DLX err: %s" % self.packetHandler.getRxPacketError(dxl_error))
OSError: DLX err: [RxPacketError] The data value exceeds the limit value!

2022-01-31T13:07:17|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\logged_quantity.py", line 860, in update_math_reverse
    lq.update_value(new_val)
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\logged_quantity.py", line 274, in update_value
    self.hardware_set_func(self.val)
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\dynamixel_servo\dynamixel_x_servo_hw.py", line 63, in write_f
    self.dev.write_value(sid, ctrl.name, new_val)
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\dynamixel_servo\dynamixel_x_servo.py", line 151, in write_value
    raise IOError("DLX err: %s" % self.packetHandler.getRxPacketError(dxl_error))
OSError: DLX err: [RxPacketError] The data value exceeds the limit value!

2022-01-31T13:07:17|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\logged_quantity.py", line 860, in update_math_reverse
    lq.update_value(new_val)
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\logged_quantity.py", line 274, in update_value
    self.hardware_set_func(self.val)
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\dynamixel_servo\dynamixel_x_servo_hw.py", line 63, in write_f
    self.dev.write_value(sid, ctrl.name, new_val)
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\dynamixel_servo\dynamixel_x_servo.py", line 151, in write_value
    raise IOError("DLX err: %s" % self.packetHandler.getRxPacketError(dxl_error))
OSError: DLX err: [RxPacketError] The data value exceeds the limit value!

2022-01-31T13:07:19|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\logged_quantity.py", line 860, in update_math_reverse
    lq.update_value(new_val)
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\logged_quantity.py", line 274, in update_value
    self.hardware_set_func(self.val)
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\dynamixel_servo\dynamixel_x_servo_hw.py", line 63, in write_f
    self.dev.write_value(sid, ctrl.name, new_val)
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\dynamixel_servo\dynamixel_x_servo.py", line 151, in write_value
    raise IOError("DLX err: %s" % self.packetHandler.getRxPacketError(dxl_error))
OSError: DLX err: [RxPacketError] The data value exceeds the limit value!

2022-01-31T13:07:20|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\logged_quantity.py", line 860, in update_math_reverse
    lq.update_value(new_val)
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\logged_quantity.py", line 274, in update_value
    self.hardware_set_func(self.val)
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\dynamixel_servo\dynamixel_x_servo_hw.py", line 63, in write_f
    self.dev.write_value(sid, ctrl.name, new_val)
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\dynamixel_servo\dynamixel_x_servo.py", line 151, in write_value
    raise IOError("DLX err: %s" % self.packetHandler.getRxPacketError(dxl_error))
OSError: DLX err: [RxPacketError] The data value exceeds the limit value!

2022-01-31T13:07:27|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\logged_quantity.py", line 860, in update_math_reverse
    lq.update_value(new_val)
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\logged_quantity.py", line 274, in update_value
    self.hardware_set_func(self.val)
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\dynamixel_servo\dynamixel_x_servo_hw.py", line 63, in write_f
    self.dev.write_value(sid, ctrl.name, new_val)
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\dynamixel_servo\dynamixel_x_servo.py", line 151, in write_value
    raise IOError("DLX err: %s" % self.packetHandler.getRxPacketError(dxl_error))
OSError: DLX err: [RxPacketError] The data value exceeds the limit value!

2022-01-31T13:07:29|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\logged_quantity.py", line 860, in update_math_reverse
    lq.update_value(new_val)
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\logged_quantity.py", line 274, in update_value
    self.hardware_set_func(self.val)
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\dynamixel_servo\dynamixel_x_servo_hw.py", line 63, in write_f
    self.dev.write_value(sid, ctrl.name, new_val)
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\dynamixel_servo\dynamixel_x_servo.py", line 151, in write_value
    raise IOError("DLX err: %s" % self.packetHandler.getRxPacketError(dxl_error))
OSError: DLX err: [RxPacketError] The data value exceeds the limit value!

2022-01-31T13:17:53|DEBUG|ScopeFoundryHW.ni_daq.devices.ni_counter_task|NI_CounterTask.set_channel-- Dev1/ctr0 /Dev1/PFI0
2022-01-31T13:18:02|INFO|PowerScanMeasure|power_scan start_stop True
2022-01-31T13:18:02|INFO|PowerScanMeasure|measurement power_scan start called from thread: 17212
2022-01-31T13:18:02|DEBUG|ScopeFoundryHW.thorlabs_powermeter.thorlabs_pm100d|get_auto_range '1\n'
2022-01-31T13:18:02|DEBUG|ScopeFoundryHW.thorlabs_powermeter.thorlabs_pm100d|get_auto_range '1\n'
2022-01-31T13:18:02|INFO|PowerScanMeasure|power_scan start_stop False
2022-01-31T13:18:02|INFO|PowerScanMeasure|measurement power_scan stopping run_post_run
2022-01-31T13:18:02|INFO|PowerScanMeasure|measurement power_scan interrupt called
2022-01-31T13:18:06|INFO|PowerScanMeasure|power_scan start_stop True
2022-01-31T13:18:06|INFO|PowerScanMeasure|measurement power_scan start called from thread: 17212
2022-01-31T13:18:06|INFO|PowerScanMeasure|power_scan start_stop False
2022-01-31T13:18:06|INFO|PowerScanMeasure|measurement power_scan stopping run_post_run
2022-01-31T13:18:06|INFO|PowerScanMeasure|measurement power_scan interrupt called
2022-01-31T13:18:13|INFO|PowerScanMeasure|power_scan start_stop True
2022-01-31T13:18:13|INFO|PowerScanMeasure|measurement power_scan start called from thread: 17212
2022-01-31T13:18:13|INFO|PowerScanMeasure|power_scan start_stop False
2022-01-31T13:18:14|INFO|PowerScanMeasure|measurement power_scan stopping run_post_run
2022-01-31T13:18:14|INFO|PowerScanMeasure|measurement power_scan interrupt called
2022-01-31T13:18:31|INFO|PowerScanMeasure|power_scan start_stop True
2022-01-31T13:18:31|INFO|PowerScanMeasure|measurement power_scan start called from thread: 17212
2022-01-31T13:19:54|INFO|PowerScanMeasure|power_scan start_stop False
2022-01-31T13:19:54|INFO|PowerScanMeasure|measurement power_scan stopping run_thread_run
2022-01-31T13:19:54|INFO|PowerScanMeasure|measurement power_scan interrupt called
2022-01-31T13:19:56|INFO|PowerScanMeasure|data saved E:\Natalie\220131_131955_power_scan.h5
2022-01-31T13:20:08|DEBUG|root|close
2022-01-31T13:20:12|DEBUG|root|closing
2022-01-31T13:20:12|INFO|NearFieldMicroscope|on_close
2022-01-31T13:20:12|INFO|NearFieldMicroscope|disconnecting hydraharp
2022-01-31T13:20:12|INFO|NearFieldMicroscope|disconnecting thorlabs_powermeter
2022-01-31T13:20:13|INFO|NearFieldMicroscope|disconnecting motorized_polarizer
2022-01-31T13:20:13|INFO|NearFieldMicroscope|disconnecting apd_counter
2022-01-31T13:20:13|INFO|NearFieldMicroscope|disconnecting dynamixel_servos
2022-01-31T13:20:13|INFO|NearFieldMicroscope|disconnecting power_wheel
