2021-12-09T19:17:10|INFO|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer start_stop False
2021-12-09T19:17:10|INFO|HydraHarpOptimizerMeasure|measurement hydraharp_channel_optimizer stopping stop_first
2021-12-09T19:17:10|INFO|HydraHarpHistogramMeasure|hydraharp_histogram start_stop False
2021-12-09T19:17:10|INFO|HydraHarpHistogramMeasure|measurement hydraharp_histogram stopping stop_first
2021-12-09T19:17:10|INFO|PowerScanMeasure|power_scan start_stop False
2021-12-09T19:17:10|INFO|PowerScanMeasure|measurement power_scan stopping stop_first
2021-12-09T19:17:10|INFO|PowerMeterOptimizerMeasure|powermeter_optimizer start_stop False
2021-12-09T19:17:10|INFO|PowerMeterOptimizerMeasure|measurement powermeter_optimizer stopping stop_first
2021-12-09T19:17:10|INFO|Sequencer|sequencer start_stop False
2021-12-09T19:17:10|INFO|Sequencer|measurement sequencer stopping stop_first
2021-12-09T19:17:10|INFO|APDOptimizerCBMeasurement|apd_optimizer start_stop False
2021-12-09T19:17:10|INFO|APDOptimizerCBMeasurement|measurement apd_optimizer stopping stop_first
2021-12-09T19:17:10|INFO|NearFieldMicroscope|setting up figures for hydraharp_channel_optimizer measurement hydraharp_channel_optimizer
2021-12-09T19:17:10|INFO|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer start_stop False
2021-12-09T19:17:10|INFO|HydraHarpOptimizerMeasure|measurement hydraharp_channel_optimizer stopping stop_first
2021-12-09T19:17:10|INFO|NearFieldMicroscope|setting up figures for hydraharp_histogram measurement hydraharp_histogram
2021-12-09T19:17:11|INFO|NearFieldMicroscope|setting up figures for power_scan measurement power_scan
2021-12-09T19:17:11|INFO|PowerScanMeasure|power_scan start_stop False
2021-12-09T19:17:11|INFO|PowerScanMeasure|measurement power_scan stopping stop_first
2021-12-09T19:17:11|INFO|NearFieldMicroscope|setting up figures for powermeter_optimizer measurement powermeter_optimizer
2021-12-09T19:17:11|INFO|PowerMeterOptimizerMeasure|powermeter_optimizer start_stop False
2021-12-09T19:17:11|INFO|PowerMeterOptimizerMeasure|measurement powermeter_optimizer stopping stop_first
2021-12-09T19:17:11|INFO|NearFieldMicroscope|setting up figures for sequencer measurement sequencer
2021-12-09T19:17:11|INFO|Sequencer|sequencer start_stop False
2021-12-09T19:17:11|INFO|Sequencer|measurement sequencer stopping stop_first
2021-12-09T19:17:11|WARNING|HydraHarpOptimizerMeasure|Measurement.gui is deprecated, use Measurement.app <class 'DeprecationWarning'>
2021-12-09T19:17:11|WARNING|HydraHarpHistogramMeasure|Measurement.gui is deprecated, use Measurement.app <class 'DeprecationWarning'>
2021-12-09T19:17:11|WARNING|PowerScanMeasure|Measurement.gui is deprecated, use Measurement.app <class 'DeprecationWarning'>
2021-12-09T19:17:11|WARNING|PowerMeterOptimizerMeasure|Measurement.gui is deprecated, use Measurement.app <class 'DeprecationWarning'>
2021-12-09T19:17:11|WARNING|Sequencer|Measurement.gui is deprecated, use Measurement.app <class 'DeprecationWarning'>
2021-12-09T19:17:11|WARNING|APDOptimizerCBMeasurement|Measurement.gui is deprecated, use Measurement.app <class 'DeprecationWarning'>
2021-12-09T19:17:11|INFO|NearFieldMicroscope|setting up figures for apd_optimizer measurement apd_optimizer
2021-12-09T19:17:11|INFO|APDOptimizerCBMeasurement|apd_optimizer start_stop False
2021-12-09T19:17:11|INFO|APDOptimizerCBMeasurement|measurement apd_optimizer stopping stop_first
2021-12-09T19:17:11|INFO|NearFieldMicroscope|ini settings loading from near_field_microscope_defaults.ini
2021-12-09T19:17:11|DEBUG|FileLQ|save_dir: update_value 'C:\\Users\\RAMAN\\workspace\\NearField\\NearFieldMicroscope\\data' --> 'E:\\Natalie'    sender=None
2021-12-09T19:17:11|DEBUG|FileLQ|save_dir: different values C:\Users\RAMAN\workspace\NearField\NearFieldMicroscope\data E:\Natalie
2021-12-09T19:17:11|INFO|NearFieldMicroscope|hardware/hydraharp
2021-12-09T19:17:11|INFO|NearFieldMicroscope|hardware/pololu_maestro
2021-12-09T19:17:14|INFO|NearFieldMicroscope|hardware/power_wheel
2021-12-09T19:17:14|INFO|NearFieldMicroscope|hardware/thorlabs_powermeter
2021-12-09T19:17:14|INFO|NearFieldMicroscope|hardware/motorized_polarizer
2021-12-09T19:17:14|INFO|NearFieldMicroscope|hardware/apd_counter
2021-12-09T19:17:14|INFO|NearFieldMicroscope|ini settings loaded from: near_field_microscope_defaults.ini
2021-12-09T19:17:21|DEBUG|ScopeFoundryHW.ni_daq.devices.ni_counter_task|NI_CounterTask.set_channel-- Dev1/ctr0 /Dev1/PFI0
2021-12-09T19:17:38|INFO|PowerScanMeasure|power_scan start_stop True
2021-12-09T19:17:38|INFO|PowerScanMeasure|measurement power_scan start called from thread: 7760
2021-12-09T19:17:38|DEBUG|ScopeFoundryHW.thorlabs_powermeter.thorlabs_pm100d|get_auto_range '1\n'
2021-12-09T19:17:38|DEBUG|ScopeFoundryHW.thorlabs_powermeter.thorlabs_pm100d|get_auto_range '1\n'
2021-12-09T19:17:38|INFO|PowerScanMeasure|power_scan start_stop False
2021-12-09T19:17:38|INFO|PowerScanMeasure|measurement power_scan stopping run_post_run
2021-12-09T19:17:38|INFO|PowerScanMeasure|measurement power_scan interrupt called
2021-12-09T19:17:41|INFO|PowerScanMeasure|power_scan start_stop True
2021-12-09T19:17:41|INFO|PowerScanMeasure|measurement power_scan start called from thread: 7760
2021-12-09T19:17:41|INFO|PowerScanMeasure|power_scan start_stop False
2021-12-09T19:17:41|INFO|PowerScanMeasure|measurement power_scan stopping run_post_run
2021-12-09T19:17:41|INFO|PowerScanMeasure|measurement power_scan interrupt called
2021-12-09T19:17:42|INFO|PowerScanMeasure|power_scan start_stop True
2021-12-09T19:17:42|INFO|PowerScanMeasure|measurement power_scan start called from thread: 7760
2021-12-09T19:17:46|INFO|PowerScanMeasure|power_scan start_stop False
2021-12-09T19:17:46|INFO|PowerScanMeasure|measurement power_scan stopping run_thread_run
2021-12-09T19:17:46|INFO|PowerScanMeasure|measurement power_scan interrupt called
2021-12-09T19:17:47|INFO|PowerScanMeasure|data saved E:\Natalie\211209_191747_power_scan.h5
2021-12-09T19:18:21|INFO|PowerScanMeasure|power_scan start_stop True
2021-12-09T19:18:21|INFO|PowerScanMeasure|measurement power_scan start called from thread: 7760
2021-12-09T19:18:52|INFO|PowerScanMeasure|power_scan start_stop False
2021-12-09T19:18:52|INFO|PowerScanMeasure|measurement power_scan stopping run_thread_run
2021-12-09T19:18:52|INFO|PowerScanMeasure|measurement power_scan interrupt called
2021-12-09T19:20:24|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\measurement.py", line 25, in run
    self.measurement._thread_run()
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\measurement.py", line 230, in _thread_run
    self.run()
  File "C:\Users\RAMAN\workspace\NearField\confocal_measure\power_scan.py", line 325, in run
    self.pw_target_position.update_value(self.power_wheel_position[ii])
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\logged_quantity.py", line 274, in update_value
    self.hardware_set_func(self.val)
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\thorlabs_integrated_stepper\thorlabs_integrated_stepper_motor_hw.py", line 45, in move_and_wait_scaled
    self.dev.move_and_wait(int(round(self.steps_per_deg.value*new_pos)))
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\thorlabs_integrated_stepper\thorlabs_integrated_stepper_motor_dev.py", line 186, in move_and_wait
    raise( IOError("Failed to move"))
OSError: Failed to move

2021-12-09T19:20:26|INFO|NearFieldMicroscope|ini settings loading from C:/Users/RAMAN/workspace/NearField/NearFieldMicroscope/near_field_microscope_defaults.ini
2021-12-09T19:20:26|DEBUG|FileLQ|save_dir: update_value 'E:\\Natalie' --> 'E:\\Natalie'    sender=<PyQt5.QtWidgets.QAction object at 0x000001D47065B288>
2021-12-09T19:20:26|DEBUG|FileLQ|save_dir: same_value so returning E:\Natalie E:\Natalie
2021-12-09T19:20:27|INFO|NearFieldMicroscope|hardware/hydraharp
2021-12-09T19:20:27|INFO|NearFieldMicroscope|hardware/pololu_maestro
2021-12-09T19:20:27|INFO|NearFieldMicroscope|hardware/power_wheel
2021-12-09T19:20:27|INFO|NearFieldMicroscope|hardware/thorlabs_powermeter
2021-12-09T19:20:27|INFO|NearFieldMicroscope|hardware/motorized_polarizer
2021-12-09T19:20:27|INFO|NearFieldMicroscope|hardware/apd_counter
2021-12-09T19:20:27|INFO|NearFieldMicroscope|ini settings loaded from: C:/Users/RAMAN/workspace/NearField/NearFieldMicroscope/near_field_microscope_defaults.ini
2021-12-09T19:20:34|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\base_app.py", line 851, in window_positions_load_dialog
    self.load_window_positions_json(fname)
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\base_app.py", line 968, in load_window_positions_json
    with open(fname, 'r') as infile:
FileNotFoundError: [Errno 2] No such file or directory: ''

2021-12-09T19:20:39|INFO|NearFieldMicroscope|ini settings loading from C:/Users/RAMAN/workspace/NearField/NearFieldMicroscope/near_field_microscope_defaults.ini
2021-12-09T19:20:39|DEBUG|FileLQ|save_dir: update_value 'E:\\Natalie' --> 'E:\\Natalie'    sender=<PyQt5.QtWidgets.QAction object at 0x000001D47065B288>
2021-12-09T19:20:39|DEBUG|FileLQ|save_dir: same_value so returning E:\Natalie E:\Natalie
2021-12-09T19:20:39|INFO|NearFieldMicroscope|hardware/hydraharp
2021-12-09T19:20:39|INFO|NearFieldMicroscope|hardware/pololu_maestro
2021-12-09T19:20:39|INFO|NearFieldMicroscope|hardware/power_wheel
2021-12-09T19:20:39|INFO|NearFieldMicroscope|hardware/thorlabs_powermeter
2021-12-09T19:20:39|INFO|NearFieldMicroscope|hardware/motorized_polarizer
2021-12-09T19:20:39|INFO|NearFieldMicroscope|hardware/apd_counter
2021-12-09T19:20:39|INFO|NearFieldMicroscope|ini settings loaded from: C:/Users/RAMAN/workspace/NearField/NearFieldMicroscope/near_field_microscope_defaults.ini
2021-12-09T19:21:15|INFO|NearFieldMicroscope|ini settings loading from C:/Users/RAMAN/workspace/NearField/NearFieldMicroscope/near_field_microscope_defaults.ini
2021-12-09T19:21:15|DEBUG|FileLQ|save_dir: update_value 'E:\\Natalie' --> 'E:\\Natalie'    sender=<PyQt5.QtWidgets.QAction object at 0x000001D47065B288>
2021-12-09T19:21:15|DEBUG|FileLQ|save_dir: same_value so returning E:\Natalie E:\Natalie
2021-12-09T19:21:15|INFO|NearFieldMicroscope|hardware/hydraharp
2021-12-09T19:21:15|INFO|NearFieldMicroscope|hardware/pololu_maestro
2021-12-09T19:21:15|INFO|NearFieldMicroscope|hardware/power_wheel
2021-12-09T19:21:15|INFO|NearFieldMicroscope|hardware/thorlabs_powermeter
2021-12-09T19:21:15|INFO|NearFieldMicroscope|hardware/motorized_polarizer
2021-12-09T19:21:15|INFO|NearFieldMicroscope|hardware/apd_counter
2021-12-09T19:21:15|INFO|NearFieldMicroscope|ini settings loaded from: C:/Users/RAMAN/workspace/NearField/NearFieldMicroscope/near_field_microscope_defaults.ini
2021-12-09T19:22:55|INFO|PowerScanMeasure|power_scan start_stop True
2021-12-09T19:22:55|INFO|PowerScanMeasure|measurement power_scan start called from thread: 7760
2021-12-09T19:24:36|INFO|PowerScanMeasure|power_scan start_stop False
2021-12-09T19:24:36|INFO|PowerScanMeasure|measurement power_scan stopping run_thread_run
2021-12-09T19:24:36|INFO|PowerScanMeasure|measurement power_scan interrupt called
2021-12-09T19:24:43|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\measurement.py", line 25, in run
    self.measurement._thread_run()
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\measurement.py", line 230, in _thread_run
    self.run()
  File "C:\Users\RAMAN\workspace\NearField\confocal_measure\power_scan.py", line 325, in run
    self.pw_target_position.update_value(self.power_wheel_position[ii])
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\logged_quantity.py", line 274, in update_value
    self.hardware_set_func(self.val)
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\thorlabs_integrated_stepper\thorlabs_integrated_stepper_motor_hw.py", line 45, in move_and_wait_scaled
    self.dev.move_and_wait(int(round(self.steps_per_deg.value*new_pos)))
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\thorlabs_integrated_stepper\thorlabs_integrated_stepper_motor_dev.py", line 186, in move_and_wait
    raise( IOError("Failed to move"))
OSError: Failed to move

2021-12-09T19:24:54|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\hardware.py", line 237, in enable_connection
    raise err
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\hardware.py", line 230, in enable_connection
    self.disconnect()
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\thorlabs_integrated_stepper\thorlabs_integrated_stepper_motor_hw.py", line 37, in disconnect
    self.dev.close_device()
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\thorlabs_integrated_stepper\thorlabs_integrated_stepper_motor_dev.py", line 156, in close_device
    err_msg = _err(self.isc_dll.ISC_Close(self._id))
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\thorlabs_integrated_stepper\thorlabs_integrated_stepper_motor_dev.py", line 66, in _err
    raise IOError("Thorlabs Kinesis Error [{}] {}: {} ".format(retval, err_name, description))
OSError: Thorlabs Kinesis Error [1907295952] UNKNOWN: Unknown error code. 

2021-12-09T19:27:20|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\logged_quantity.py", line 274, in update_value
    self.hardware_set_func(self.val)
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\thorlabs_integrated_stepper\thorlabs_integrated_stepper_motor_hw.py", line 45, in move_and_wait_scaled
    self.dev.move_and_wait(int(round(self.steps_per_deg.value*new_pos)))
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\thorlabs_integrated_stepper\thorlabs_integrated_stepper_motor_dev.py", line 186, in move_and_wait
    raise( IOError("Failed to move"))
OSError: Failed to move

2021-12-09T19:29:03|INFO|PowerScanMeasure|power_scan start_stop True
2021-12-09T19:29:03|INFO|PowerScanMeasure|measurement power_scan start called from thread: 7760
2021-12-09T19:31:20|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\measurement.py", line 25, in run
    self.measurement._thread_run()
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\measurement.py", line 230, in _thread_run
    self.run()
  File "C:\Users\RAMAN\workspace\NearField\confocal_measure\power_scan.py", line 325, in run
    self.pw_target_position.update_value(self.power_wheel_position[ii])
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\logged_quantity.py", line 274, in update_value
    self.hardware_set_func(self.val)
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\thorlabs_integrated_stepper\thorlabs_integrated_stepper_motor_hw.py", line 45, in move_and_wait_scaled
    self.dev.move_and_wait(int(round(self.steps_per_deg.value*new_pos)))
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\thorlabs_integrated_stepper\thorlabs_integrated_stepper_motor_dev.py", line 186, in move_and_wait
    raise( IOError("Failed to move"))
OSError: Failed to move

2021-12-09T19:31:21|INFO|PowerScanMeasure|power_scan start_stop False
2021-12-09T19:31:21|INFO|PowerScanMeasure|measurement power_scan stopping run_post_run
2021-12-09T19:31:21|INFO|PowerScanMeasure|measurement power_scan interrupt called
2021-12-09T19:41:07|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\logged_quantity.py", line 274, in update_value
    self.hardware_set_func(self.val)
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\thorlabs_integrated_stepper\thorlabs_integrated_stepper_motor_hw.py", line 53, in move_and_wait_scaled
    return
AttributeError: 'ThorlabsIntegratedStepperMottorHW' object has no attribute 'stop_profiled'

2021-12-09T19:52:23|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\logged_quantity.py", line 274, in update_value
    self.hardware_set_func(self.val)
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\thorlabs_integrated_stepper\thorlabs_integrated_stepper_motor_hw.py", line 54, in move_and_wait_scaled
    self.stop_profiled()
AttributeError: 'ThorlabsIntegratedStepperMottorHW' object has no attribute 'stop_profiled'

2021-12-09T20:05:59|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\hardware.py", line 237, in enable_connection
    raise err
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\hardware.py", line 230, in enable_connection
    self.disconnect()
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\thorlabs_integrated_stepper\thorlabs_integrated_stepper_motor_hw.py", line 37, in disconnect
    def disconnect(self):
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\thorlabs_integrated_stepper\thorlabs_integrated_stepper_motor_dev.py", line 156, in close_device
    return self._id.decode()
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\thorlabs_integrated_stepper\thorlabs_integrated_stepper_motor_dev.py", line 66, in _err
OSError: Thorlabs Kinesis Error [2076188464] UNKNOWN: Unknown error code. 

2021-12-09T20:19:27|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\hardware.py", line 220, in enable_connection
    raise err
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\hardware.py", line 210, in enable_connection
    self.connect()
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\thorlabs_powermeter\thorlabs_powermeter.py", line 53, in connect
    self.power_meter = ThorlabsPM100D(debug=self.settings['debug_mode'], port=self.settings['port'])
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\thorlabs_powermeter\thorlabs_pm100d.py", line 35, in __init__
    self.pm = self.visa_resource_manager.get_instrument(port)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyvisa\highlevel.py", line 3358, in get_instrument
    resource_name, access_mode, open_timeout, resource_pyclass, **kwargs
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyvisa\highlevel.py", line 3304, in open_resource
    res.open(access_mode, open_timeout)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyvisa\resources\resource.py", line 298, in open
    self._resource_name, access_mode, open_timeout
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyvisa\highlevel.py", line 3232, in open_bare_resource
    return self.visalib.open(self.session, resource_name, access_mode, open_timeout)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyvisa\ctwrapper\functions.py", line 1852, in open
    session, resource_name, access_mode, open_timeout, byref(out_session)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyvisa\ctwrapper\highlevel.py", line 222, in _return_handler
    return self.handle_return_value(session, ret_value)  # type: ignore
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyvisa\highlevel.py", line 251, in handle_return_value
    raise errors.VisaIOError(rv)
pyvisa.errors.VisaIOError: VI_ERROR_RSRC_NFOUND (-1073807343): Insufficient location information or the requested device or resource is not present in the system.

2021-12-09T20:19:34|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\hardware.py", line 220, in enable_connection
    raise err
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\hardware.py", line 210, in enable_connection
    self.connect()
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\thorlabs_powermeter\thorlabs_powermeter.py", line 53, in connect
    self.power_meter = ThorlabsPM100D(debug=self.settings['debug_mode'], port=self.settings['port'])
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\thorlabs_powermeter\thorlabs_pm100d.py", line 35, in __init__
    self.pm = self.visa_resource_manager.get_instrument(port)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyvisa\highlevel.py", line 3358, in get_instrument
    resource_name, access_mode, open_timeout, resource_pyclass, **kwargs
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyvisa\highlevel.py", line 3304, in open_resource
    res.open(access_mode, open_timeout)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyvisa\resources\resource.py", line 298, in open
    self._resource_name, access_mode, open_timeout
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyvisa\highlevel.py", line 3232, in open_bare_resource
    return self.visalib.open(self.session, resource_name, access_mode, open_timeout)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyvisa\ctwrapper\functions.py", line 1852, in open
    session, resource_name, access_mode, open_timeout, byref(out_session)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyvisa\ctwrapper\highlevel.py", line 222, in _return_handler
    return self.handle_return_value(session, ret_value)  # type: ignore
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyvisa\highlevel.py", line 251, in handle_return_value
    raise errors.VisaIOError(rv)
pyvisa.errors.VisaIOError: VI_ERROR_RSRC_NFOUND (-1073807343): Insufficient location information or the requested device or resource is not present in the system.

2021-12-09T20:20:51|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\hardware.py", line 220, in enable_connection
    raise err
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\hardware.py", line 210, in enable_connection
    self.connect()
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\thorlabs_powermeter\thorlabs_powermeter.py", line 53, in connect
    self.power_meter = ThorlabsPM100D(debug=self.settings['debug_mode'], port=self.settings['port'])
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\thorlabs_powermeter\thorlabs_pm100d.py", line 35, in __init__
    self.pm = self.visa_resource_manager.get_instrument(port)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyvisa\highlevel.py", line 3358, in get_instrument
    resource_name, access_mode, open_timeout, resource_pyclass, **kwargs
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyvisa\highlevel.py", line 3304, in open_resource
    res.open(access_mode, open_timeout)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyvisa\resources\resource.py", line 298, in open
    self._resource_name, access_mode, open_timeout
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyvisa\highlevel.py", line 3232, in open_bare_resource
    return self.visalib.open(self.session, resource_name, access_mode, open_timeout)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyvisa\ctwrapper\functions.py", line 1852, in open
    session, resource_name, access_mode, open_timeout, byref(out_session)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyvisa\ctwrapper\highlevel.py", line 222, in _return_handler
    return self.handle_return_value(session, ret_value)  # type: ignore
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyvisa\highlevel.py", line 251, in handle_return_value
    raise errors.VisaIOError(rv)
pyvisa.errors.VisaIOError: VI_ERROR_RSRC_NFOUND (-1073807343): Insufficient location information or the requested device or resource is not present in the system.

2021-12-09T20:20:55|DEBUG|ScopeFoundryHW.thorlabs_powermeter.thorlabs_pm100d|get_auto_range '1\n'
2021-12-09T20:20:55|DEBUG|ScopeFoundryHW.thorlabs_powermeter.thorlabs_pm100d|get_auto_range '1\n'
2021-12-09T20:20:57|INFO|PowerMeterOptimizerMeasure|powermeter_optimizer start_stop True
2021-12-09T20:20:57|INFO|PowerMeterOptimizerMeasure|measurement powermeter_optimizer start called from thread: 7760
2021-12-09T20:21:21|INFO|PowerMeterOptimizerMeasure|powermeter_optimizer start_stop False
2021-12-09T20:21:21|INFO|PowerMeterOptimizerMeasure|measurement powermeter_optimizer stopping run_thread_run
2021-12-09T20:21:21|INFO|PowerMeterOptimizerMeasure|measurement powermeter_optimizer interrupt called
2021-12-09T20:42:13|DEBUG|root|close
2021-12-09T20:42:15|DEBUG|root|closing
2021-12-09T20:42:15|INFO|NearFieldMicroscope|on_close
2021-12-09T20:42:15|INFO|NearFieldMicroscope|disconnecting hydraharp
2021-12-09T20:42:15|INFO|NearFieldMicroscope|disconnecting pololu_maestro
2021-12-09T20:42:15|INFO|NearFieldMicroscope|disconnecting power_wheel
2021-12-09T20:42:15|INFO|NearFieldMicroscope|disconnecting thorlabs_powermeter
2021-12-09T20:42:15|INFO|NearFieldMicroscope|disconnecting motorized_polarizer
2021-12-09T20:42:15|ERROR|NearFieldMicroscope|tried to disconnect motorized_polarizer: Thorlabs Kinesis Error [1957549104] UNKNOWN: Unknown error code. 
2021-12-09T20:42:16|INFO|NearFieldMicroscope|disconnecting apd_counter
