2021-12-09T15:42:36|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\RAMAN\.p2\pool\plugins\org.python.pydev.core_9.2.0.202110311311\pysrc\pydevd.py", line 3338, in <module>
    main()
  File "C:\Users\RAMAN\.p2\pool\plugins\org.python.pydev.core_9.2.0.202110311311\pysrc\pydevd.py", line 3331, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Users\RAMAN\.p2\pool\plugins\org.python.pydev.core_9.2.0.202110311311\pysrc\pydevd.py", line 2398, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "C:\Users\RAMAN\.p2\pool\plugins\org.python.pydev.core_9.2.0.202110311311\pysrc\pydevd.py", line 2405, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Users\RAMAN\.p2\pool\plugins\org.python.pydev.core_9.2.0.202110311311\pysrc\_pydev_imps\_pydev_execfile.py", line 25, in execfile
    exec(compile(contents + "\n", file, 'exec'), glob, loc)
  File "C:\Users\RAMAN\workspace\NearField\NearFieldMicroscope\near_field_microscope_app.py", line 218, in <module>
    app = NearFieldMicroscope(sys.argv)
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\base_app.py", line 338, in __init__
    self.setup()
  File "C:\Users\RAMAN\workspace\NearField\NearFieldMicroscope\near_field_microscope_app.py", line 50, in setup
    self.add_hardware(ThorlabsStepperControllerHW())
TypeError: __init__() missing 1 required positional argument: 'app'

