2022-01-31T19:00:42|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\dynamixel_servo\dynamixel_single_hw.py", line 67, in set_mode
    self.servos.settings[S['servo_name']+'_torque'] = False
AttributeError: 'DynamixelServoHW' object has no attribute 'servos'

2022-01-31T19:00:42|INFO|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer start_stop False
2022-01-31T19:00:42|INFO|HydraHarpOptimizerMeasure|measurement hydraharp_channel_optimizer stopping stop_first
2022-01-31T19:00:42|INFO|HydraHarpHistogramMeasure|hydraharp_histogram start_stop False
2022-01-31T19:00:42|INFO|HydraHarpHistogramMeasure|measurement hydraharp_histogram stopping stop_first
2022-01-31T19:00:42|INFO|PowerScanMeasure|power_scan start_stop False
2022-01-31T19:00:42|INFO|PowerScanMeasure|measurement power_scan stopping stop_first
2022-01-31T19:00:42|INFO|PowerMeterOptimizerMeasure|powermeter_optimizer start_stop False
2022-01-31T19:00:42|INFO|PowerMeterOptimizerMeasure|measurement powermeter_optimizer stopping stop_first
2022-01-31T19:00:42|INFO|Sequencer|sequencer start_stop False
2022-01-31T19:00:42|INFO|Sequencer|measurement sequencer stopping stop_first
2022-01-31T19:00:42|INFO|APDOptimizerCBMeasurement|apd_optimizer start_stop False
2022-01-31T19:00:42|INFO|APDOptimizerCBMeasurement|measurement apd_optimizer stopping stop_first
2022-01-31T19:00:42|INFO|NearFieldMicroscope|setting up figures for hydraharp_channel_optimizer measurement hydraharp_channel_optimizer
2022-01-31T19:00:42|INFO|HydraHarpOptimizerMeasure|hydraharp_channel_optimizer start_stop False
2022-01-31T19:00:42|INFO|HydraHarpOptimizerMeasure|measurement hydraharp_channel_optimizer stopping stop_first
2022-01-31T19:00:42|INFO|NearFieldMicroscope|setting up figures for hydraharp_histogram measurement hydraharp_histogram
2022-01-31T19:00:42|INFO|NearFieldMicroscope|setting up figures for power_scan measurement power_scan
2022-01-31T19:00:42|INFO|PowerScanMeasure|power_scan start_stop False
2022-01-31T19:00:42|INFO|PowerScanMeasure|measurement power_scan stopping stop_first
2022-01-31T19:00:42|INFO|NearFieldMicroscope|setting up figures for powermeter_optimizer measurement powermeter_optimizer
2022-01-31T19:00:42|INFO|PowerMeterOptimizerMeasure|powermeter_optimizer start_stop False
2022-01-31T19:00:42|INFO|PowerMeterOptimizerMeasure|measurement powermeter_optimizer stopping stop_first
2022-01-31T19:00:42|INFO|NearFieldMicroscope|setting up figures for sequencer measurement sequencer
2022-01-31T19:00:42|INFO|Sequencer|sequencer start_stop False
2022-01-31T19:00:42|INFO|Sequencer|measurement sequencer stopping stop_first
2022-01-31T19:00:42|WARNING|HydraHarpOptimizerMeasure|Measurement.gui is deprecated, use Measurement.app <class 'DeprecationWarning'>
2022-01-31T19:00:42|WARNING|HydraHarpHistogramMeasure|Measurement.gui is deprecated, use Measurement.app <class 'DeprecationWarning'>
2022-01-31T19:00:42|WARNING|PowerScanMeasure|Measurement.gui is deprecated, use Measurement.app <class 'DeprecationWarning'>
2022-01-31T19:00:42|WARNING|PowerMeterOptimizerMeasure|Measurement.gui is deprecated, use Measurement.app <class 'DeprecationWarning'>
2022-01-31T19:00:42|WARNING|Sequencer|Measurement.gui is deprecated, use Measurement.app <class 'DeprecationWarning'>
2022-01-31T19:00:42|WARNING|APDOptimizerCBMeasurement|Measurement.gui is deprecated, use Measurement.app <class 'DeprecationWarning'>
2022-01-31T19:00:42|INFO|NearFieldMicroscope|setting up figures for apd_optimizer measurement apd_optimizer
2022-01-31T19:00:42|INFO|APDOptimizerCBMeasurement|apd_optimizer start_stop False
2022-01-31T19:00:42|INFO|APDOptimizerCBMeasurement|measurement apd_optimizer stopping stop_first
2022-01-31T19:00:43|INFO|NearFieldMicroscope|ini settings loading from near_field_microscope_defaults.ini
2022-01-31T19:00:43|DEBUG|FileLQ|save_dir: update_value 'C:\\Users\\RAMAN\\workspace\\NearField\\NearFieldMicroscope\\data' --> 'E:\\Natalie'    sender=None
2022-01-31T19:00:43|DEBUG|FileLQ|save_dir: different values C:\Users\RAMAN\workspace\NearField\NearFieldMicroscope\data E:\Natalie
2022-01-31T19:00:43|INFO|NearFieldMicroscope|hardware/hydraharp
2022-01-31T19:00:43|INFO|NearFieldMicroscope|hardware/thorlabs_powermeter
2022-01-31T19:00:43|INFO|NearFieldMicroscope|hardware/motorized_polarizer
2022-01-31T19:00:43|INFO|NearFieldMicroscope|hardware/apd_counter
2022-01-31T19:00:43|INFO|NearFieldMicroscope|hardware/dynamixel_servos
2022-01-31T19:00:43|INFO|NearFieldMicroscope|hardware/power_wheel
2022-01-31T19:00:43|INFO|NearFieldMicroscope|-->Failed to load config for hardware/power_wheel/pos_scale, new val 280: KeyError('pos_scale')
2022-01-31T19:00:43|INFO|NearFieldMicroscope|ini settings loaded from: near_field_microscope_defaults.ini
2022-01-31T19:01:01|DEBUG|ScopeFoundryHW.thorlabs_powermeter.thorlabs_pm100d|get_auto_range '1\n'
2022-01-31T19:01:01|DEBUG|ScopeFoundryHW.thorlabs_powermeter.thorlabs_pm100d|get_auto_range '1\n'
2022-01-31T19:01:04|INFO|PowerMeterOptimizerMeasure|powermeter_optimizer start_stop True
2022-01-31T19:01:04|INFO|PowerMeterOptimizerMeasure|measurement powermeter_optimizer start called from thread: 9680
2022-01-31T19:02:56|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\logged_quantity.py", line 860, in update_math_reverse
    lq.update_value(new_val)
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\logged_quantity.py", line 274, in update_value
    self.hardware_set_func(self.val)
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\dynamixel_servo\dynamixel_x_servo_hw.py", line 63, in write_f
    self.dev.write_value(sid, ctrl.name, new_val)
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\dynamixel_servo\dynamixel_x_servo.py", line 151, in write_value
    raise IOError("DLX err: %s" % self.packetHandler.getRxPacketError(dxl_error))
OSError: DLX err: [RxPacketError] The data value exceeds the limit value!

2022-01-31T19:03:00|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\logged_quantity.py", line 860, in update_math_reverse
    lq.update_value(new_val)
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\logged_quantity.py", line 274, in update_value
    self.hardware_set_func(self.val)
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\dynamixel_servo\dynamixel_x_servo_hw.py", line 63, in write_f
    self.dev.write_value(sid, ctrl.name, new_val)
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\dynamixel_servo\dynamixel_x_servo.py", line 151, in write_value
    raise IOError("DLX err: %s" % self.packetHandler.getRxPacketError(dxl_error))
OSError: DLX err: [RxPacketError] The data value exceeds the limit value!

2022-02-01T12:29:51|INFO|PowerScanMeasure|power_scan start_stop True
2022-02-01T12:29:51|INFO|PowerScanMeasure|measurement power_scan start called from thread: 9680
2022-02-01T12:29:51|INFO|PowerScanMeasure|power_scan start_stop False
2022-02-01T12:29:51|INFO|PowerScanMeasure|measurement power_scan stopping run_post_run
2022-02-01T12:29:51|INFO|PowerScanMeasure|measurement power_scan interrupt called
2022-02-01T12:29:55|INFO|PowerScanMeasure|power_scan start_stop True
2022-02-01T12:29:55|INFO|PowerScanMeasure|measurement power_scan start called from thread: 9680
2022-02-01T12:29:58|WARNING|LoggedQuantity|count_rate read_from_hardware called when not connected to hardware
2022-02-01T12:29:59|WARNING|LoggedQuantity|count_rate read_from_hardware called when not connected to hardware
2022-02-01T12:30:00|WARNING|LoggedQuantity|count_rate read_from_hardware called when not connected to hardware
2022-02-01T12:30:01|WARNING|LoggedQuantity|count_rate read_from_hardware called when not connected to hardware
2022-02-01T12:30:01|WARNING|LoggedQuantity|count_rate read_from_hardware called when not connected to hardware
2022-02-01T12:30:03|WARNING|LoggedQuantity|count_rate read_from_hardware called when not connected to hardware
2022-02-01T12:30:03|WARNING|LoggedQuantity|count_rate read_from_hardware called when not connected to hardware
2022-02-01T12:30:04|WARNING|LoggedQuantity|count_rate read_from_hardware called when not connected to hardware
2022-02-01T12:30:05|WARNING|LoggedQuantity|count_rate read_from_hardware called when not connected to hardware
2022-02-01T12:30:06|WARNING|LoggedQuantity|count_rate read_from_hardware called when not connected to hardware
2022-02-01T12:30:09|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\thorlabs_powermeter\thorlabs_pm100d.py", line 68, in ask
    resp = self.pm.query(cmd)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyvisa\resources\messagebased.py", line 644, in query
    return self.read()
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyvisa\resources\messagebased.py", line 486, in read
    message = self._read_raw().decode(enco)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyvisa\resources\messagebased.py", line 442, in _read_raw
    chunk, status = self.visalib.read(self.session, size)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyvisa\ctwrapper\functions.py", line 2337, in read
    ret = library.viRead(session, buffer, count, byref(return_count))
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyvisa\ctwrapper\highlevel.py", line 222, in _return_handler
    return self.handle_return_value(session, ret_value)  # type: ignore
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyvisa\highlevel.py", line 251, in handle_return_value
    raise errors.VisaIOError(rv)
pyvisa.errors.VisaIOError: VI_ERROR_TMO (-1073807339): Timeout expired before operation completed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\measurement.py", line 25, in run
    self.measurement._thread_run()
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\measurement.py", line 230, in _thread_run
    self.run()
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\thorlabs_powermeter\powermeter_optimizer.py", line 89, in run
    pow_reading = self.powermeter.settings.power.read_from_hardware()
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\logged_quantity.py", line 195, in read_from_hardware
    val = self.hardware_read_func()
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\thorlabs_powermeter\thorlabs_pm100d.py", line 141, in measure_power
    self.power = float(self.ask("MEAS:POW?"))
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\thorlabs_powermeter\thorlabs_pm100d.py", line 70, in ask
    resp = self.pm.ask(cmd) # Deprecated pyvisa method --> replaced by query()
AttributeError: 'USBInstrument' object has no attribute 'ask'

2022-02-01T12:30:09|INFO|PowerMeterOptimizerMeasure|powermeter_optimizer start_stop False
2022-02-01T12:30:09|INFO|PowerMeterOptimizerMeasure|measurement powermeter_optimizer stopping run_post_run
2022-02-01T12:30:09|INFO|PowerMeterOptimizerMeasure|measurement powermeter_optimizer interrupt called
2022-02-01T12:30:15|INFO|PowerMeterOptimizerMeasure|powermeter_optimizer start_stop True
2022-02-01T12:30:15|INFO|PowerMeterOptimizerMeasure|measurement powermeter_optimizer start called from thread: 9680
2022-02-01T12:30:17|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\thorlabs_powermeter\thorlabs_pm100d.py", line 68, in ask
    resp = self.pm.query(cmd)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyvisa\resources\messagebased.py", line 638, in query
    self.write(message)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyvisa\resources\messagebased.py", line 197, in write
    count = self.write_raw(message.encode(enco))
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyvisa\resources\messagebased.py", line 157, in write_raw
    return self.visalib.write(self.session, message)[0]
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyvisa\ctwrapper\functions.py", line 2796, in write
    ret = library.viWrite(session, data, len(data), byref(return_count))
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyvisa\ctwrapper\highlevel.py", line 222, in _return_handler
    return self.handle_return_value(session, ret_value)  # type: ignore
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyvisa\highlevel.py", line 251, in handle_return_value
    raise errors.VisaIOError(rv)
pyvisa.errors.VisaIOError: VI_ERROR_TMO (-1073807339): Timeout expired before operation completed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\measurement.py", line 25, in run
    self.measurement._thread_run()
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\measurement.py", line 230, in _thread_run
    self.run()
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\thorlabs_powermeter\powermeter_optimizer.py", line 89, in run
    pow_reading = self.powermeter.settings.power.read_from_hardware()
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\logged_quantity.py", line 195, in read_from_hardware
    val = self.hardware_read_func()
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\thorlabs_powermeter\thorlabs_pm100d.py", line 141, in measure_power
    self.power = float(self.ask("MEAS:POW?"))
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\thorlabs_powermeter\thorlabs_pm100d.py", line 70, in ask
    resp = self.pm.ask(cmd) # Deprecated pyvisa method --> replaced by query()
AttributeError: 'USBInstrument' object has no attribute 'ask'

2022-02-01T12:30:17|INFO|PowerMeterOptimizerMeasure|powermeter_optimizer start_stop False
2022-02-01T12:30:17|INFO|PowerMeterOptimizerMeasure|measurement powermeter_optimizer stopping run_post_run
2022-02-01T12:30:17|INFO|PowerMeterOptimizerMeasure|measurement powermeter_optimizer interrupt called
2022-02-01T12:30:20|WARNING|LoggedQuantity|count_rate read_from_hardware called when not connected to hardware
2022-02-01T12:30:52|INFO|PowerScanMeasure|power_scan start_stop False
2022-02-01T12:30:52|INFO|PowerScanMeasure|measurement power_scan stopping run_thread_run
2022-02-01T12:30:52|INFO|PowerScanMeasure|measurement power_scan interrupt called
2022-02-01T12:30:53|INFO|PowerScanMeasure|data saved E:\Natalie\220201_123053_power_scan.h5
2022-02-01T12:30:56|INFO|PowerMeterOptimizerMeasure|powermeter_optimizer start_stop True
2022-02-01T12:30:56|INFO|PowerMeterOptimizerMeasure|measurement powermeter_optimizer start called from thread: 9680
2022-02-01T12:30:57|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\thorlabs_powermeter\thorlabs_pm100d.py", line 68, in ask
    resp = self.pm.query(cmd)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyvisa\resources\messagebased.py", line 644, in query
    return self.read()
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyvisa\resources\messagebased.py", line 486, in read
    message = self._read_raw().decode(enco)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyvisa\resources\messagebased.py", line 442, in _read_raw
    chunk, status = self.visalib.read(self.session, size)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyvisa\ctwrapper\functions.py", line 2337, in read
    ret = library.viRead(session, buffer, count, byref(return_count))
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyvisa\ctwrapper\highlevel.py", line 222, in _return_handler
    return self.handle_return_value(session, ret_value)  # type: ignore
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyvisa\highlevel.py", line 251, in handle_return_value
    raise errors.VisaIOError(rv)
pyvisa.errors.VisaIOError: VI_ERROR_TMO (-1073807339): Timeout expired before operation completed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\measurement.py", line 25, in run
    self.measurement._thread_run()
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\measurement.py", line 230, in _thread_run
    self.run()
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\thorlabs_powermeter\powermeter_optimizer.py", line 89, in run
    pow_reading = self.powermeter.settings.power.read_from_hardware()
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\logged_quantity.py", line 195, in read_from_hardware
    val = self.hardware_read_func()
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\thorlabs_powermeter\thorlabs_pm100d.py", line 141, in measure_power
    self.power = float(self.ask("MEAS:POW?"))
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\thorlabs_powermeter\thorlabs_pm100d.py", line 70, in ask
    resp = self.pm.ask(cmd) # Deprecated pyvisa method --> replaced by query()
AttributeError: 'USBInstrument' object has no attribute 'ask'

2022-02-01T12:30:57|INFO|PowerMeterOptimizerMeasure|powermeter_optimizer start_stop False
2022-02-01T12:30:57|INFO|PowerMeterOptimizerMeasure|measurement powermeter_optimizer stopping run_post_run
2022-02-01T12:30:57|INFO|PowerMeterOptimizerMeasure|measurement powermeter_optimizer interrupt called
2022-02-01T12:30:59|INFO|PowerScanMeasure|power_scan start_stop True
2022-02-01T12:30:59|INFO|PowerScanMeasure|measurement power_scan start called from thread: 9680
2022-02-01T12:31:02|WARNING|LoggedQuantity|count_rate read_from_hardware called when not connected to hardware
2022-02-01T12:31:03|WARNING|LoggedQuantity|count_rate read_from_hardware called when not connected to hardware
2022-02-01T12:31:04|WARNING|LoggedQuantity|count_rate read_from_hardware called when not connected to hardware
2022-02-01T12:31:05|WARNING|LoggedQuantity|count_rate read_from_hardware called when not connected to hardware
2022-02-01T12:31:06|WARNING|LoggedQuantity|count_rate read_from_hardware called when not connected to hardware
2022-02-01T12:31:07|WARNING|LoggedQuantity|count_rate read_from_hardware called when not connected to hardware
2022-02-01T12:31:08|WARNING|LoggedQuantity|count_rate read_from_hardware called when not connected to hardware
2022-02-01T12:31:09|WARNING|LoggedQuantity|count_rate read_from_hardware called when not connected to hardware
2022-02-01T12:31:09|WARNING|LoggedQuantity|count_rate read_from_hardware called when not connected to hardware
2022-02-01T12:31:10|WARNING|LoggedQuantity|count_rate read_from_hardware called when not connected to hardware
2022-02-01T12:31:11|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\logged_quantity.py", line 860, in update_math_reverse
    lq.update_value(new_val)
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\logged_quantity.py", line 274, in update_value
    self.hardware_set_func(self.val)
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\dynamixel_servo\dynamixel_x_servo_hw.py", line 63, in write_f
    self.dev.write_value(sid, ctrl.name, new_val)
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\dynamixel_servo\dynamixel_x_servo.py", line 149, in write_value
    raise IOError("DLX comm fail: %s" % self.packetHandler.getTxRxResult(dxl_comm_result))
OSError: DLX comm fail: [TxRxResult] Incorrect status packet!

2022-02-01T12:31:11|WARNING|LoggedQuantity|count_rate read_from_hardware called when not connected to hardware
2022-02-01T12:31:11|INFO|PowerScanMeasure|data saved E:\Natalie\220201_123111_power_scan.h5
2022-02-01T12:31:12|INFO|PowerScanMeasure|power_scan start_stop False
2022-02-01T12:31:12|INFO|PowerScanMeasure|measurement power_scan stopping run_post_run
2022-02-01T12:31:12|INFO|PowerScanMeasure|measurement power_scan interrupt called
2022-02-01T12:31:19|INFO|PowerMeterOptimizerMeasure|powermeter_optimizer start_stop True
2022-02-01T12:31:19|INFO|PowerMeterOptimizerMeasure|measurement powermeter_optimizer start called from thread: 9680
2022-02-01T12:31:20|INFO|PowerScanMeasure|power_scan start_stop True
2022-02-01T12:31:20|INFO|PowerScanMeasure|measurement power_scan start called from thread: 9680
2022-02-01T12:31:23|WARNING|LoggedQuantity|count_rate read_from_hardware called when not connected to hardware
2022-02-01T12:31:24|WARNING|LoggedQuantity|count_rate read_from_hardware called when not connected to hardware
2022-02-01T12:31:25|WARNING|LoggedQuantity|count_rate read_from_hardware called when not connected to hardware
2022-02-01T12:31:26|WARNING|LoggedQuantity|count_rate read_from_hardware called when not connected to hardware
2022-02-01T12:31:26|WARNING|LoggedQuantity|count_rate read_from_hardware called when not connected to hardware
2022-02-01T12:31:27|WARNING|LoggedQuantity|count_rate read_from_hardware called when not connected to hardware
2022-02-01T12:31:28|WARNING|LoggedQuantity|count_rate read_from_hardware called when not connected to hardware
2022-02-01T12:31:29|WARNING|LoggedQuantity|count_rate read_from_hardware called when not connected to hardware
2022-02-01T12:31:30|WARNING|LoggedQuantity|count_rate read_from_hardware called when not connected to hardware
2022-02-01T12:31:30|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\logged_quantity.py", line 860, in update_math_reverse
    lq.update_value(new_val)
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\logged_quantity.py", line 274, in update_value
    self.hardware_set_func(self.val)
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\dynamixel_servo\dynamixel_x_servo_hw.py", line 63, in write_f
    self.dev.write_value(sid, ctrl.name, new_val)
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\dynamixel_servo\dynamixel_x_servo.py", line 149, in write_value
    raise IOError("DLX comm fail: %s" % self.packetHandler.getTxRxResult(dxl_comm_result))
OSError: DLX comm fail: [TxRxResult] Incorrect status packet!

2022-02-01T12:31:31|WARNING|LoggedQuantity|count_rate read_from_hardware called when not connected to hardware
2022-02-01T12:31:32|WARNING|LoggedQuantity|count_rate read_from_hardware called when not connected to hardware
2022-02-01T12:31:32|INFO|PowerScanMeasure|data saved E:\Natalie\220201_123132_power_scan.h5
2022-02-01T12:31:32|INFO|PowerScanMeasure|power_scan start_stop False
2022-02-01T12:31:32|INFO|PowerScanMeasure|measurement power_scan stopping run_post_run
2022-02-01T12:31:32|INFO|PowerScanMeasure|measurement power_scan interrupt called
2022-02-01T12:31:40|INFO|PowerScanMeasure|power_scan start_stop True
2022-02-01T12:31:40|INFO|PowerScanMeasure|measurement power_scan start called from thread: 9680
2022-02-01T12:31:43|WARNING|LoggedQuantity|count_rate read_from_hardware called when not connected to hardware
2022-02-01T12:31:44|WARNING|LoggedQuantity|count_rate read_from_hardware called when not connected to hardware
2022-02-01T12:31:45|WARNING|LoggedQuantity|count_rate read_from_hardware called when not connected to hardware
2022-02-01T12:31:45|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\logged_quantity.py", line 860, in update_math_reverse
    lq.update_value(new_val)
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\logged_quantity.py", line 274, in update_value
    self.hardware_set_func(self.val)
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\dynamixel_servo\dynamixel_x_servo_hw.py", line 63, in write_f
    self.dev.write_value(sid, ctrl.name, new_val)
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\dynamixel_servo\dynamixel_x_servo.py", line 149, in write_value
    raise IOError("DLX comm fail: %s" % self.packetHandler.getTxRxResult(dxl_comm_result))
OSError: DLX comm fail: [TxRxResult] Incorrect status packet!

2022-02-01T12:31:46|WARNING|LoggedQuantity|count_rate read_from_hardware called when not connected to hardware
2022-02-01T12:31:47|WARNING|LoggedQuantity|count_rate read_from_hardware called when not connected to hardware
2022-02-01T12:31:48|WARNING|LoggedQuantity|count_rate read_from_hardware called when not connected to hardware
2022-02-01T12:31:48|WARNING|LoggedQuantity|count_rate read_from_hardware called when not connected to hardware
2022-02-01T12:31:49|WARNING|LoggedQuantity|count_rate read_from_hardware called when not connected to hardware
2022-02-01T12:31:50|WARNING|LoggedQuantity|count_rate read_from_hardware called when not connected to hardware
2022-02-01T12:31:51|WARNING|LoggedQuantity|count_rate read_from_hardware called when not connected to hardware
2022-02-01T12:31:52|WARNING|LoggedQuantity|count_rate read_from_hardware called when not connected to hardware
2022-02-01T12:31:52|INFO|PowerScanMeasure|data saved E:\Natalie\220201_123152_power_scan.h5
2022-02-01T12:31:52|INFO|PowerScanMeasure|power_scan start_stop False
2022-02-01T12:31:52|INFO|PowerScanMeasure|measurement power_scan stopping run_post_run
2022-02-01T12:31:53|INFO|PowerScanMeasure|measurement power_scan interrupt called
2022-02-01T18:08:21|DEBUG|ScopeFoundryHW.ni_daq.devices.ni_counter_task|NI_CounterTask.set_channel-- Dev1/ctr0 /Dev1/PFI0
2022-02-01T18:08:32|INFO|APDOptimizerCBMeasurement|apd_optimizer start_stop True
2022-02-01T18:08:32|INFO|APDOptimizerCBMeasurement|measurement apd_optimizer start called from thread: 9680
2022-02-01T18:34:03|INFO|APDOptimizerCBMeasurement|apd_optimizer start_stop False
2022-02-01T18:34:03|INFO|APDOptimizerCBMeasurement|measurement apd_optimizer stopping run_thread_run
2022-02-01T18:34:03|INFO|APDOptimizerCBMeasurement|measurement apd_optimizer interrupt called
2022-02-01T18:38:07|INFO|PowerScanMeasure|power_scan start_stop True
2022-02-01T18:38:07|INFO|PowerScanMeasure|measurement power_scan start called from thread: 9680
2022-02-01T18:44:08|INFO|PowerScanMeasure|data saved E:\Natalie\220201_184408_power_scan.h5
2022-02-01T18:44:08|INFO|PowerScanMeasure|power_scan start_stop False
2022-02-01T18:44:08|INFO|PowerScanMeasure|measurement power_scan stopping run_post_run
2022-02-01T18:44:08|INFO|PowerScanMeasure|measurement power_scan interrupt called
2022-02-01T18:44:57|INFO|PowerScanMeasure|power_scan start_stop True
2022-02-01T18:44:57|INFO|PowerScanMeasure|measurement power_scan start called from thread: 9680
2022-02-01T18:51:33|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\thorlabs_powermeter\thorlabs_pm100d.py", line 68, in ask
    resp = self.pm.query(cmd)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyvisa\resources\messagebased.py", line 644, in query
    return self.read()
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyvisa\resources\messagebased.py", line 486, in read
    message = self._read_raw().decode(enco)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyvisa\resources\messagebased.py", line 442, in _read_raw
    chunk, status = self.visalib.read(self.session, size)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyvisa\ctwrapper\functions.py", line 2337, in read
    ret = library.viRead(session, buffer, count, byref(return_count))
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyvisa\ctwrapper\highlevel.py", line 222, in _return_handler
    return self.handle_return_value(session, ret_value)  # type: ignore
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyvisa\highlevel.py", line 251, in handle_return_value
    raise errors.VisaIOError(rv)
pyvisa.errors.VisaIOError: VI_ERROR_TMO (-1073807339): Timeout expired before operation completed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\measurement.py", line 25, in run
    self.measurement._thread_run()
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\measurement.py", line 230, in _thread_run
    self.run()
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\thorlabs_powermeter\powermeter_optimizer.py", line 89, in run
    pow_reading = self.powermeter.settings.power.read_from_hardware()
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\logged_quantity.py", line 195, in read_from_hardware
    val = self.hardware_read_func()
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\thorlabs_powermeter\thorlabs_pm100d.py", line 141, in measure_power
    self.power = float(self.ask("MEAS:POW?"))
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\thorlabs_powermeter\thorlabs_pm100d.py", line 70, in ask
    resp = self.pm.ask(cmd) # Deprecated pyvisa method --> replaced by query()
AttributeError: 'USBInstrument' object has no attribute 'ask'

2022-02-01T18:51:33|INFO|PowerMeterOptimizerMeasure|powermeter_optimizer start_stop False
2022-02-01T18:51:33|INFO|PowerMeterOptimizerMeasure|measurement powermeter_optimizer stopping run_post_run
2022-02-01T18:51:33|INFO|PowerMeterOptimizerMeasure|measurement powermeter_optimizer interrupt called
2022-02-01T19:01:44|INFO|PowerMeterOptimizerMeasure|powermeter_optimizer start_stop True
2022-02-01T19:01:45|INFO|PowerMeterOptimizerMeasure|measurement powermeter_optimizer start called from thread: 9680
2022-02-01T19:01:46|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\thorlabs_powermeter\thorlabs_pm100d.py", line 68, in ask
    resp = self.pm.query(cmd)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyvisa\resources\messagebased.py", line 638, in query
    self.write(message)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyvisa\resources\messagebased.py", line 197, in write
    count = self.write_raw(message.encode(enco))
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyvisa\resources\messagebased.py", line 157, in write_raw
    return self.visalib.write(self.session, message)[0]
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyvisa\ctwrapper\functions.py", line 2796, in write
    ret = library.viWrite(session, data, len(data), byref(return_count))
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyvisa\ctwrapper\highlevel.py", line 222, in _return_handler
    return self.handle_return_value(session, ret_value)  # type: ignore
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyvisa\highlevel.py", line 251, in handle_return_value
    raise errors.VisaIOError(rv)
pyvisa.errors.VisaIOError: VI_ERROR_TMO (-1073807339): Timeout expired before operation completed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\measurement.py", line 25, in run
    self.measurement._thread_run()
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\measurement.py", line 230, in _thread_run
    self.run()
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\thorlabs_powermeter\powermeter_optimizer.py", line 89, in run
    pow_reading = self.powermeter.settings.power.read_from_hardware()
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\logged_quantity.py", line 195, in read_from_hardware
    val = self.hardware_read_func()
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\thorlabs_powermeter\thorlabs_pm100d.py", line 141, in measure_power
    self.power = float(self.ask("MEAS:POW?"))
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\thorlabs_powermeter\thorlabs_pm100d.py", line 70, in ask
    resp = self.pm.ask(cmd) # Deprecated pyvisa method --> replaced by query()
AttributeError: 'USBInstrument' object has no attribute 'ask'

2022-02-01T19:01:46|INFO|PowerMeterOptimizerMeasure|powermeter_optimizer start_stop False
2022-02-01T19:01:46|INFO|PowerMeterOptimizerMeasure|measurement powermeter_optimizer stopping run_post_run
2022-02-01T19:01:46|INFO|PowerMeterOptimizerMeasure|measurement powermeter_optimizer interrupt called
2022-02-01T19:01:49|INFO|PowerMeterOptimizerMeasure|powermeter_optimizer start_stop True
2022-02-01T19:01:49|INFO|PowerMeterOptimizerMeasure|measurement powermeter_optimizer start called from thread: 9680
2022-02-01T19:01:50|INFO|PowerMeterOptimizerMeasure|powermeter_optimizer start_stop False
2022-02-01T19:01:50|INFO|PowerMeterOptimizerMeasure|measurement powermeter_optimizer stopping run_thread_run
2022-02-01T19:01:50|INFO|PowerMeterOptimizerMeasure|measurement powermeter_optimizer interrupt called
2022-02-01T19:01:50|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\thorlabs_powermeter\thorlabs_pm100d.py", line 68, in ask
    resp = self.pm.query(cmd)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyvisa\resources\messagebased.py", line 638, in query
    self.write(message)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyvisa\resources\messagebased.py", line 197, in write
    count = self.write_raw(message.encode(enco))
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyvisa\resources\messagebased.py", line 157, in write_raw
    return self.visalib.write(self.session, message)[0]
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyvisa\ctwrapper\functions.py", line 2796, in write
    ret = library.viWrite(session, data, len(data), byref(return_count))
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyvisa\ctwrapper\highlevel.py", line 222, in _return_handler
    return self.handle_return_value(session, ret_value)  # type: ignore
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyvisa\highlevel.py", line 251, in handle_return_value
    raise errors.VisaIOError(rv)
pyvisa.errors.VisaIOError: VI_ERROR_TMO (-1073807339): Timeout expired before operation completed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\measurement.py", line 25, in run
    self.measurement._thread_run()
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\measurement.py", line 230, in _thread_run
    self.run()
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\thorlabs_powermeter\powermeter_optimizer.py", line 89, in run
    pow_reading = self.powermeter.settings.power.read_from_hardware()
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\logged_quantity.py", line 195, in read_from_hardware
    val = self.hardware_read_func()
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\thorlabs_powermeter\thorlabs_pm100d.py", line 141, in measure_power
    self.power = float(self.ask("MEAS:POW?"))
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\thorlabs_powermeter\thorlabs_pm100d.py", line 70, in ask
    resp = self.pm.ask(cmd) # Deprecated pyvisa method --> replaced by query()
AttributeError: 'USBInstrument' object has no attribute 'ask'

2022-02-01T19:05:40|INFO|PowerScanMeasure|data saved E:\Natalie\220201_190540_power_scan.h5
2022-02-01T19:05:40|INFO|PowerScanMeasure|power_scan start_stop False
2022-02-01T19:05:40|INFO|PowerScanMeasure|measurement power_scan stopping run_post_run
2022-02-01T19:05:41|INFO|PowerScanMeasure|measurement power_scan interrupt called
2022-02-01T19:07:19|INFO|PowerMeterOptimizerMeasure|powermeter_optimizer start_stop True
2022-02-01T19:07:19|INFO|PowerMeterOptimizerMeasure|measurement powermeter_optimizer start called from thread: 9680
2022-02-01T19:07:40|INFO|PowerMeterOptimizerMeasure|powermeter_optimizer start_stop False
2022-02-01T19:07:40|INFO|PowerMeterOptimizerMeasure|measurement powermeter_optimizer stopping run_thread_run
2022-02-01T19:07:40|INFO|PowerMeterOptimizerMeasure|measurement powermeter_optimizer interrupt called
2022-02-01T19:14:42|INFO|PowerMeterOptimizerMeasure|powermeter_optimizer start_stop True
2022-02-01T19:14:42|INFO|PowerMeterOptimizerMeasure|measurement powermeter_optimizer start called from thread: 9680
2022-02-01T19:27:43|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\ni_daq\devices\ni_counter_task.py", line 152, in read_buffer
    self.task.ReadCounterF64(-1, timeout, data, count, mx.byref(read_count), None)
  File "<string>", line 3, in ReadCounterF64
  File "<string>", line 2, in function
  File "C:\ProgramData\Anaconda3\lib\site-packages\PyDAQmx\DAQmxFunctions.py", line 62, in mafunction
    raise exception_class(errBuff.value.decode("utf-8"), f.__name__)
PyDAQmx.DAQmxFunctions.SamplesNoLongerAvailableError: The application is not able to keep up with the hardware acquisition.

Increasing the buffer size, reading the data more frequently, or specifying a fixed number of samples to read instead of reading all available samples might correct the problem.
Property: DAQmx_Read_RelativeTo
Corresponding Value: DAQmx_Val_CurrReadPos
Property: DAQmx_Read_Offset
Corresponding Value: 0

Task Name: _unnamedTask<0>

Status Code: -200279
 in function DAQmxReadCounterF64

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 232, in 'calling callback function'
  File "C:\ProgramData\Anaconda3\lib\site-packages\PyDAQmx\Task.py", line 46, in EveryNCallback_py
    getattr(self,name)()
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\ni_daq\hw\ni_freq_counter_callback.py", line 87, in counter_callback
    raise err
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\ni_daq\hw\ni_freq_counter_callback.py", line 83, in counter_callback
    self.current_count = self.counter_task.read_buffer(count=self.n_samples_cb)[-1]
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\ni_daq\devices\ni_counter_task.py", line 154, in read_buffer
    self.error(err)
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\ni_daq\devices\ni_task_wrap.py", line 42, in error
    logger.error('Error calling "{}": {}'.format( err.fname, err.mess ))
AttributeError: 'SamplesNoLongerAvailableError' object has no attribute 'mess'

2022-02-01T20:08:11|INFO|PowerScanMeasure|power_scan start_stop True
2022-02-01T20:08:11|INFO|PowerScanMeasure|measurement power_scan start called from thread: 9680
2022-02-01T20:08:24|INFO|PowerScanMeasure|power_scan start_stop False
2022-02-01T20:08:24|INFO|PowerScanMeasure|measurement power_scan stopping run_thread_run
2022-02-01T20:08:24|INFO|PowerScanMeasure|measurement power_scan interrupt called
2022-02-01T20:08:25|INFO|PowerScanMeasure|data saved E:\Natalie\220201_200824_power_scan.h5
2022-02-01T20:08:30|INFO|PowerScanMeasure|power_scan start_stop True
2022-02-01T20:08:30|INFO|PowerScanMeasure|measurement power_scan start called from thread: 9680
2022-02-01T20:08:51|INFO|PowerScanMeasure|data saved E:\Natalie\220201_200851_power_scan.h5
2022-02-01T20:08:52|INFO|PowerScanMeasure|power_scan start_stop False
2022-02-01T20:08:52|INFO|PowerScanMeasure|measurement power_scan stopping run_post_run
2022-02-01T20:08:52|INFO|PowerScanMeasure|measurement power_scan interrupt called
2022-02-01T20:09:36|INFO|PowerScanMeasure|power_scan start_stop True
2022-02-01T20:09:36|INFO|PowerScanMeasure|measurement power_scan start called from thread: 9680
2022-02-01T20:09:58|INFO|PowerScanMeasure|data saved E:\Natalie\220201_200958_power_scan.h5
2022-02-01T20:09:58|INFO|PowerScanMeasure|power_scan start_stop False
2022-02-01T20:09:58|INFO|PowerScanMeasure|measurement power_scan stopping run_post_run
2022-02-01T20:09:58|INFO|PowerScanMeasure|measurement power_scan interrupt called
2022-02-01T20:10:09|INFO|PowerScanMeasure|power_scan start_stop True
2022-02-01T20:10:09|INFO|PowerScanMeasure|measurement power_scan start called from thread: 9680
2022-02-01T20:10:31|INFO|PowerScanMeasure|data saved E:\Natalie\220201_201031_power_scan.h5
2022-02-01T20:10:31|INFO|PowerScanMeasure|power_scan start_stop False
2022-02-01T20:10:31|INFO|PowerScanMeasure|measurement power_scan stopping run_post_run
2022-02-01T20:10:31|INFO|PowerScanMeasure|measurement power_scan interrupt called
2022-02-01T20:12:11|INFO|PowerScanMeasure|power_scan start_stop True
2022-02-01T20:12:11|INFO|PowerScanMeasure|measurement power_scan start called from thread: 9680
2022-02-01T20:12:32|INFO|PowerScanMeasure|data saved E:\Natalie\220201_201232_power_scan.h5
2022-02-01T20:12:32|INFO|PowerScanMeasure|power_scan start_stop False
2022-02-01T20:12:32|INFO|PowerScanMeasure|measurement power_scan stopping run_post_run
2022-02-01T20:12:33|INFO|PowerScanMeasure|measurement power_scan interrupt called
2022-02-01T20:14:35|INFO|APDOptimizerCBMeasurement|apd_optimizer start_stop True
2022-02-01T20:14:35|INFO|APDOptimizerCBMeasurement|measurement apd_optimizer start called from thread: 9680
2022-02-01T20:21:20|INFO|PowerScanMeasure|power_scan start_stop True
2022-02-01T20:21:20|INFO|PowerScanMeasure|measurement power_scan start called from thread: 9680
2022-02-01T20:21:32|INFO|PowerScanMeasure|data saved E:\Natalie\220201_202132_power_scan.h5
2022-02-01T20:21:32|INFO|PowerScanMeasure|power_scan start_stop False
2022-02-01T20:21:32|INFO|PowerScanMeasure|measurement power_scan stopping run_post_run
2022-02-01T20:21:32|INFO|PowerScanMeasure|measurement power_scan interrupt called
2022-02-01T20:22:00|INFO|PowerScanMeasure|power_scan start_stop True
2022-02-01T20:22:00|INFO|PowerScanMeasure|measurement power_scan start called from thread: 9680
2022-02-01T20:22:24|INFO|PowerScanMeasure|data saved E:\Natalie\220201_202224_power_scan.h5
2022-02-01T20:22:24|INFO|PowerScanMeasure|power_scan start_stop False
2022-02-01T20:22:25|INFO|PowerScanMeasure|measurement power_scan stopping run_post_run
2022-02-01T20:22:25|INFO|PowerScanMeasure|measurement power_scan interrupt called
2022-02-01T20:24:28|INFO|PowerScanMeasure|power_scan start_stop True
2022-02-01T20:24:28|INFO|PowerScanMeasure|measurement power_scan start called from thread: 9680
2022-02-01T20:24:52|INFO|PowerScanMeasure|data saved E:\Natalie\220201_202452_power_scan.h5
2022-02-01T20:24:52|INFO|PowerScanMeasure|power_scan start_stop False
2022-02-01T20:24:52|INFO|PowerScanMeasure|measurement power_scan stopping run_post_run
2022-02-01T20:24:52|INFO|PowerScanMeasure|measurement power_scan interrupt called
2022-02-01T20:25:52|INFO|PowerScanMeasure|power_scan start_stop True
2022-02-01T20:25:52|INFO|PowerScanMeasure|measurement power_scan start called from thread: 9680
2022-02-01T20:26:16|INFO|PowerScanMeasure|data saved E:\Natalie\220201_202616_power_scan.h5
2022-02-01T20:26:16|INFO|PowerScanMeasure|power_scan start_stop False
2022-02-01T20:26:16|INFO|PowerScanMeasure|measurement power_scan stopping run_post_run
2022-02-01T20:26:16|INFO|PowerScanMeasure|measurement power_scan interrupt called
2022-02-01T20:27:22|INFO|PowerScanMeasure|power_scan start_stop True
2022-02-01T20:27:22|INFO|PowerScanMeasure|measurement power_scan start called from thread: 9680
2022-02-01T20:28:38|INFO|PowerScanMeasure|data saved E:\Natalie\220201_202838_power_scan.h5
2022-02-01T20:28:38|INFO|PowerScanMeasure|power_scan start_stop False
2022-02-01T20:28:38|INFO|PowerScanMeasure|measurement power_scan stopping run_post_run
2022-02-01T20:28:38|INFO|PowerScanMeasure|measurement power_scan interrupt called
2022-02-01T21:12:03|DEBUG|root|close
2022-02-01T21:12:05|DEBUG|root|closing
2022-02-01T21:12:05|INFO|NearFieldMicroscope|on_close
2022-02-01T21:12:05|INFO|NearFieldMicroscope|disconnecting hydraharp
2022-02-01T21:12:05|INFO|NearFieldMicroscope|disconnecting thorlabs_powermeter
2022-02-01T21:12:05|WARNING|LoggedQuantity|power read_from_hardware called when not connected to hardware
2022-02-01T21:12:05|INFO|NearFieldMicroscope|disconnecting motorized_polarizer
2022-02-01T21:12:05|INFO|NearFieldMicroscope|disconnecting apd_counter
2022-02-01T21:12:05|WARNING|LoggedQuantity|power read_from_hardware called when not connected to hardware
2022-02-01T21:12:05|INFO|NearFieldMicroscope|disconnecting dynamixel_servos
2022-02-01T21:12:06|WARNING|LoggedQuantity|power read_from_hardware called when not connected to hardware
2022-02-01T21:12:06|INFO|NearFieldMicroscope|disconnecting power_wheel
2022-02-01T21:12:06|WARNING|LoggedQuantity|power read_from_hardware called when not connected to hardware
2022-02-01T21:12:06|WARNING|LoggedQuantity|power read_from_hardware called when not connected to hardware
2022-02-01T21:12:06|WARNING|LoggedQuantity|power read_from_hardware called when not connected to hardware
2022-02-01T21:12:06|WARNING|LoggedQuantity|power read_from_hardware called when not connected to hardware
2022-02-01T21:12:06|WARNING|LoggedQuantity|power read_from_hardware called when not connected to hardware
2022-02-01T21:12:06|WARNING|LoggedQuantity|power read_from_hardware called when not connected to hardware
2022-02-01T21:12:06|WARNING|LoggedQuantity|power read_from_hardware called when not connected to hardware
2022-02-01T21:12:06|WARNING|LoggedQuantity|power read_from_hardware called when not connected to hardware
2022-02-01T21:12:07|WARNING|LoggedQuantity|power read_from_hardware called when not connected to hardware
2022-02-01T21:12:07|WARNING|LoggedQuantity|power read_from_hardware called when not connected to hardware
2022-02-01T21:12:07|WARNING|LoggedQuantity|power read_from_hardware called when not connected to hardware
2022-02-01T21:12:07|WARNING|LoggedQuantity|power read_from_hardware called when not connected to hardware
2022-02-01T21:12:07|WARNING|LoggedQuantity|power read_from_hardware called when not connected to hardware
2022-02-01T21:12:07|WARNING|LoggedQuantity|power read_from_hardware called when not connected to hardware
2022-02-01T21:12:07|WARNING|LoggedQuantity|power read_from_hardware called when not connected to hardware
2022-02-01T21:12:07|WARNING|LoggedQuantity|power read_from_hardware called when not connected to hardware
2022-02-01T21:12:07|WARNING|LoggedQuantity|power read_from_hardware called when not connected to hardware
2022-02-01T21:12:07|WARNING|LoggedQuantity|power read_from_hardware called when not connected to hardware
2022-02-01T21:12:08|WARNING|LoggedQuantity|power read_from_hardware called when not connected to hardware
2022-02-01T21:12:08|WARNING|LoggedQuantity|power read_from_hardware called when not connected to hardware
2022-02-01T21:12:08|WARNING|LoggedQuantity|power read_from_hardware called when not connected to hardware
2022-02-01T21:12:08|WARNING|LoggedQuantity|power read_from_hardware called when not connected to hardware
2022-02-01T21:12:08|WARNING|LoggedQuantity|power read_from_hardware called when not connected to hardware
2022-02-01T21:12:08|WARNING|LoggedQuantity|power read_from_hardware called when not connected to hardware
2022-02-01T21:12:08|WARNING|LoggedQuantity|power read_from_hardware called when not connected to hardware
2022-02-01T21:12:08|WARNING|LoggedQuantity|power read_from_hardware called when not connected to hardware
2022-02-01T21:12:08|WARNING|LoggedQuantity|power read_from_hardware called when not connected to hardware
2022-02-01T21:12:08|WARNING|LoggedQuantity|power read_from_hardware called when not connected to hardware
2022-02-01T21:12:09|WARNING|LoggedQuantity|power read_from_hardware called when not connected to hardware
2022-02-01T21:12:09|WARNING|LoggedQuantity|power read_from_hardware called when not connected to hardware
2022-02-01T21:12:09|WARNING|LoggedQuantity|power read_from_hardware called when not connected to hardware
2022-02-01T21:12:09|WARNING|LoggedQuantity|power read_from_hardware called when not connected to hardware
2022-02-01T21:12:09|WARNING|LoggedQuantity|power read_from_hardware called when not connected to hardware
2022-02-01T21:12:09|WARNING|LoggedQuantity|power read_from_hardware called when not connected to hardware
2022-02-01T21:12:09|WARNING|LoggedQuantity|power read_from_hardware called when not connected to hardware
2022-02-01T21:12:09|WARNING|LoggedQuantity|power read_from_hardware called when not connected to hardware
2022-02-01T21:12:09|WARNING|LoggedQuantity|power read_from_hardware called when not connected to hardware
2022-02-01T21:12:09|WARNING|LoggedQuantity|power read_from_hardware called when not connected to hardware
2022-02-01T21:12:10|WARNING|LoggedQuantity|power read_from_hardware called when not connected to hardware
2022-02-01T21:12:10|WARNING|LoggedQuantity|power read_from_hardware called when not connected to hardware
2022-02-01T21:12:10|WARNING|LoggedQuantity|power read_from_hardware called when not connected to hardware
2022-02-01T21:12:10|WARNING|LoggedQuantity|power read_from_hardware called when not connected to hardware
2022-02-01T21:12:10|WARNING|LoggedQuantity|power read_from_hardware called when not connected to hardware
2022-02-01T21:12:10|WARNING|LoggedQuantity|power read_from_hardware called when not connected to hardware
2022-02-01T21:12:10|WARNING|LoggedQuantity|power read_from_hardware called when not connected to hardware
2022-02-01T21:12:10|WARNING|LoggedQuantity|power read_from_hardware called when not connected to hardware
2022-02-01T21:12:10|WARNING|LoggedQuantity|power read_from_hardware called when not connected to hardware
2022-02-01T21:12:10|WARNING|LoggedQuantity|power read_from_hardware called when not connected to hardware
2022-02-01T21:12:11|WARNING|LoggedQuantity|power read_from_hardware called when not connected to hardware
2022-02-01T21:12:11|WARNING|LoggedQuantity|power read_from_hardware called when not connected to hardware
2022-02-01T21:12:11|WARNING|LoggedQuantity|power read_from_hardware called when not connected to hardware
2022-02-01T21:12:11|WARNING|LoggedQuantity|power read_from_hardware called when not connected to hardware
2022-02-01T21:12:11|WARNING|LoggedQuantity|power read_from_hardware called when not connected to hardware
2022-02-01T21:12:11|WARNING|LoggedQuantity|power read_from_hardware called when not connected to hardware
