2021-12-08T17:12:23|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "near_field_microscope_app.py", line 214, in <module>
    app = NearFieldMicroscope(sys.argv)
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\base_app.py", line 338, in __init__
    self.setup()
  File "near_field_microscope_app.py", line 202, in setup
    from ScopeFoundryHW.ni_daq.hw.ni_freq_counter_callback import NI_FreqCounterCallBackHW
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\ni_daq\__init__.py", line 4, in <module>
    from ScopeFoundryHW.ni_daq.hw.ni_adc_hw import NI_ADC_HW
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\ni_daq\hw\ni_adc_hw.py", line 2, in <module>
    from ScopeFoundryHW.ni_daq.devices.NI_Daq import NI_AdcTask
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\ni_daq\devices\__init__.py", line 1, in <module>
    from .ni_task_wrap import NamedTask, NI_TaskWrap
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\ni_daq\devices\ni_task_wrap.py", line 1, in <module>
    import PyDAQmx as mx
  File "C:\Users\RAMAN\.conda\envs\scopefoundry\lib\site-packages\PyDAQmx\__init__.py", line 3, in <module>
    from DAQmxTypes import *
ModuleNotFoundError: No module named 'DAQmxTypes'

