2022-01-31T12:05:17|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\hardware.py", line 210, in enable_connection
    self.connect()
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\dynamixel_servo\dynamixel_x_servo_hw.py", line 37, in connect
    self.dev = DynamixelServos(port=self.settings['port'])
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\dynamixel_servo\dynamixel_x_servo.py", line 111, in __init__
    success = self.portHandler.openPort()
  File "C:\ProgramData\Anaconda3\lib\site-packages\dynamixel_sdk\port_handler.py", line 44, in openPort
    return self.setBaudRate(self.baudrate)
  File "C:\ProgramData\Anaconda3\lib\site-packages\dynamixel_sdk\port_handler.py", line 68, in setBaudRate
    return self.setupPort(baud)
  File "C:\ProgramData\Anaconda3\lib\site-packages\dynamixel_sdk\port_handler.py", line 120, in setupPort
    timeout=0
  File "C:\ProgramData\Anaconda3\lib\site-packages\serial\serialwin32.py", line 33, in __init__
    super(Serial, self).__init__(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\serial\serialutil.py", line 244, in __init__
    self.open()
  File "C:\ProgramData\Anaconda3\lib\site-packages\serial\serialwin32.py", line 64, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM10': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\hardware.py", line 231, in enable_connection
    self.tree_item.setText(1,'X')
AttributeError: 'DynamixelXServosHW' object has no attribute 'tree_item'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\hardware.py", line 235, in enable_connection
    self.tree_item.setText(1,'?')
AttributeError: 'DynamixelXServosHW' object has no attribute 'tree_item'

2022-01-31T12:05:17|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\hardware.py", line 210, in enable_connection
    self.connect()
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\dynamixel_servo\dynamixel_x_servo_hw.py", line 37, in connect
    self.dev = DynamixelServos(port=self.settings['port'])
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\dynamixel_servo\dynamixel_x_servo.py", line 111, in __init__
    success = self.portHandler.openPort()
  File "C:\ProgramData\Anaconda3\lib\site-packages\dynamixel_sdk\port_handler.py", line 44, in openPort
    return self.setBaudRate(self.baudrate)
  File "C:\ProgramData\Anaconda3\lib\site-packages\dynamixel_sdk\port_handler.py", line 68, in setBaudRate
    return self.setupPort(baud)
  File "C:\ProgramData\Anaconda3\lib\site-packages\dynamixel_sdk\port_handler.py", line 120, in setupPort
    timeout=0
  File "C:\ProgramData\Anaconda3\lib\site-packages\serial\serialwin32.py", line 33, in __init__
    super(Serial, self).__init__(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\serial\serialutil.py", line 244, in __init__
    self.open()
  File "C:\ProgramData\Anaconda3\lib\site-packages\serial\serialwin32.py", line 64, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM10': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\hardware.py", line 254, in on_connection_failed
    self.tree_item.setText(1,'!')
AttributeError: 'DynamixelXServosHW' object has no attribute 'tree_item'

2022-01-31T12:05:17|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\hardware.py", line 220, in enable_connection
    raise err
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundry\hardware.py", line 210, in enable_connection
    self.connect()
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\dynamixel_servo\dynamixel_x_servo_hw.py", line 37, in connect
    self.dev = DynamixelServos(port=self.settings['port'])
  File "C:\Users\RAMAN\workspace\NearField\ScopeFoundryHW\dynamixel_servo\dynamixel_x_servo.py", line 111, in __init__
    success = self.portHandler.openPort()
  File "C:\ProgramData\Anaconda3\lib\site-packages\dynamixel_sdk\port_handler.py", line 44, in openPort
    return self.setBaudRate(self.baudrate)
  File "C:\ProgramData\Anaconda3\lib\site-packages\dynamixel_sdk\port_handler.py", line 68, in setBaudRate
    return self.setupPort(baud)
  File "C:\ProgramData\Anaconda3\lib\site-packages\dynamixel_sdk\port_handler.py", line 120, in setupPort
    timeout=0
  File "C:\ProgramData\Anaconda3\lib\site-packages\serial\serialwin32.py", line 33, in __init__
    super(Serial, self).__init__(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\serial\serialutil.py", line 244, in __init__
    self.open()
  File "C:\ProgramData\Anaconda3\lib\site-packages\serial\serialwin32.py", line 64, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM10': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)

